// Auto-generated by tools/paperforge
// Do not edit manually

export interface PaperForgeEntry {
  id: string;
  name: string;
  postUrl?: string;
  folder: string;
}

export const PAPERFORGE_ENTRIES: PaperForgeEntry[] = [
  {
    id: "1",
    name: "Goblin Warrior",
    postUrl: "https://www.patreon.com/posts/free-files-base-10749718",
    folder: "0001",
  },
  {
    id: "2",
    name: "Goblin Archer",
    postUrl: "https://www.patreon.com/posts/free-files-11213955",
    folder: "0002",
  },
  {
    id: "3",
    name: "Goblin Spearman",
    postUrl: "https://www.patreon.com/posts/free-files-11310899",
    folder: "0003",
  },
  {
    id: "4",
    name: "Goblin Elder",
    postUrl: "https://www.patreon.com/posts/free-files-11444800",
    folder: "0004",
  },
  {
    id: "5",
    name: "Goblin Boss",
    postUrl: "https://www.patreon.com/posts/free-files-11589769",
    folder: "0005",
  },
  {
    id: "6",
    name: "Barbarian",
    postUrl: "https://www.patreon.com/posts/free-files-11703527",
    folder: "0006",
  },
  {
    id: "7",
    name: "Spectator",
    postUrl: "https://www.patreon.com/posts/free-files-11836131",
    folder: "0007",
  },
  {
    id: "8",
    name: "Ghast",
    postUrl: "https://www.patreon.com/posts/free-files-12141052",
    folder: "0008",
  },
  {
    id: "9",
    name: "Kobold",
    postUrl: "https://www.patreon.com/posts/free-files-12452706",
    folder: "0009",
  },
  {
    id: "10",
    name: "Kobold Sorceror",
    postUrl: "https://www.patreon.com/posts/free-files-12874549",
    folder: "0010",
  },
  {
    id: "11",
    name: "Winged Kobold",
    postUrl: "https://www.patreon.com/posts/free-files-13082785",
    folder: "0011",
  },
  {
    id: "12",
    name: "Ogre",
    postUrl: "https://www.patreon.com/file?h=13276940&m=1008167",
    folder: "0012",
  },
  {
    id: "13",
    name: "Human Thief",
    postUrl: "https://www.patreon.com/posts/free-files-13706016",
    folder: "0013",
  },
  {
    id: "14",
    name: "Halfling Assassin",
    postUrl: "https://www.patreon.com/posts/free-files-13846536",
    folder: "0014",
  },
  {
    id: "15",
    name: "Large Bear",
    postUrl: "https://www.patreon.com/posts/free-files-13969830",
    folder: "0015",
  },
  {
    id: "16",
    name: "Wolf",
    postUrl: "https://www.patreon.com/posts/free-files-14085414",
    folder: "0016",
  },
  {
    id: "17",
    name: "Bandit Captain",
    postUrl: "https://www.patreon.com/posts/free-files-14216453",
    folder: "0017",
  },
  {
    id: "17b",
    name: "Bandit (Crossbow)",
    postUrl: "https://www.patreon.com/posts/free-files-14216453",
    folder: "017b",
  },
  {
    id: "17c",
    name: "Bandit (Daggers)",
    postUrl: "https://www.patreon.com/posts/free-files-14216453",
    folder: "017c",
  },
  {
    id: "17d",
    name: "Bandit (Sword)",
    postUrl: "https://www.patreon.com/posts/free-files-14216453",
    folder: "017d",
  },
  {
    id: "17e",
    name: "Bandit (Axes)",
    postUrl: "https://www.patreon.com/posts/free-files-14216453",
    folder: "017e",
  },
  {
    id: "18",
    name: "Panther",
    postUrl: "https://www.patreon.com/posts/free-files-14406874",
    folder: "0018",
  },
  {
    id: "19",
    name: "Giant Poisonous Snake",
    postUrl: "https://www.patreon.com/posts/free-files-14534953",
    folder: "0019",
  },
  {
    id: "20",
    name: "Erinyes",
    postUrl: "https://www.patreon.com/posts/free-files-14651672",
    folder: "0020",
  },
  {
    id: "21",
    name: "Griffon",
    postUrl: "https://www.patreon.com/posts/free-files-14774227",
    folder: "0021",
  },
  {
    id: "22",
    name: "Dwarf Fighter",
    postUrl: "https://www.patreon.com/posts/free-files-14886502",
    folder: "0022",
  },
  {
    id: "23",
    name: "Monk",
    postUrl: "https://www.patreon.com/posts/free-files-15010372",
    folder: "0023",
  },
  {
    id: "24",
    name: "Dwarf Fighter",
    postUrl: "https://www.patreon.com/posts/free-files-15136843",
    folder: "0024",
  },
  {
    id: "25",
    name: "Owlbear",
    postUrl: "https://www.patreon.com/posts/free-files-15346895",
    folder: "0025",
  },
  {
    id: "25b",
    name: "Owlbear Cub",
    postUrl: "https://www.patreon.com/posts/free-files-15346895",
    folder: "025b",
  },
  {
    id: "26",
    name: "Knight",
    postUrl: "https://www.patreon.com/posts/free-files-15450981",
    folder: "0026",
  },
  {
    id: "26b",
    name: "Squire",
    postUrl: "https://www.patreon.com/posts/free-files-15450981",
    folder: "026b",
  },
  {
    id: "27",
    name: "Bard",
    postUrl: "https://www.patreon.com/posts/free-files-15558074",
    folder: "0027",
  },
  {
    id: "28",
    name: "Barlgura",
    postUrl: "https://www.patreon.com/posts/release-28-15724795",
    folder: "0028",
  },
  {
    id: "29",
    name: "Centaur",
    postUrl: "https://www.patreon.com/posts/29-centaur-15934826",
    folder: "0029",
  },
  {
    id: "30",
    name: "Ninja",
    postUrl: "https://www.patreon.com/posts/30-ninja-16277617",
    folder: "0030",
  },
  {
    id: "31",
    name: "Manes",
    postUrl: "https://www.patreon.com/posts/31-manes-16541986",
    folder: "0031",
  },
  {
    id: "32",
    name: "Gnoll Hunter",
    postUrl: "https://www.patreon.com/posts/32-33-gnoll-16801938",
    folder: "0032",
  },
  {
    id: "33",
    name: "Gnoll Warrior",
    postUrl: "https://www.patreon.com/posts/32-33-gnoll-16801938",
    folder: "0033",
  },
  {
    id: "34",
    name: "Flind",
    postUrl: "https://www.patreon.com/posts/34-flind-16933680",
    folder: "0034",
  },
  {
    id: "35",
    name: "GnollCaster",
    postUrl: "https://www.patreon.com/posts/35-36-gnoll-and-17256502",
    folder: "0035",
  },
  {
    id: "36",
    name: "Hyena",
    postUrl: "https://www.patreon.com/posts/35-36-gnoll-and-17256502",
    folder: "0036",
  },
  {
    id: "37",
    name: "Whiterling",
    postUrl: "https://www.patreon.com/posts/37-gnoll-17656550",
    folder: "0037",
  },
  {
    id: "38",
    name: "Shoosuva",
    postUrl: "https://www.patreon.com/posts/38-shoosuva-17942958",
    folder: "0038",
  },
  {
    id: "39",
    name: "Leucrotta",
    postUrl: "https://www.patreon.com/posts/39-leucrotta-17943074",
    folder: "0039",
  },
  {
    id: "40",
    name: "Vistana Tiefling",
    postUrl: "https://www.patreon.com/posts/40-vistana-18066778",
    folder: "0040",
  },
  {
    id: "41",
    name: "Giant Gnoll",
    postUrl: "https://www.patreon.com/posts/41-giant-gnoll-18228101",
    folder: "0041",
  },
  {
    id: "42",
    name: "Treasure Goblin",
    postUrl: "https://www.patreon.com/posts/42-treasure-18355534",
    folder: "0042",
  },
  {
    id: "43",
    name: "Samurai",
    postUrl: "https://www.patreon.com/posts/43-samurai-18536874",
    folder: "0043",
  },
  {
    id: "44",
    name: "Worg",
    postUrl: "https://www.patreon.com/posts/44-worg-18897463",
    folder: "0044",
  },
  {
    id: "45",
    name: "Worg Riders 1",
    postUrl: "https://www.patreon.com/posts/45-worg-riders-18897516",
    folder: "0045",
  },
  {
    id: "45b",
    name: "Worg Riders",
    postUrl: "https://www.patreon.com/posts/45-worg-riders-18897516",
    folder: "045b",
  },
  {
    id: "46",
    name: "Centaur",
    postUrl: "https://www.patreon.com/posts/46-centaur-2-19375032",
    folder: "0046",
  },
  {
    id: "47",
    name: "Minotaur 1",
    postUrl: "https://www.patreon.com/posts/47-minotaurs-19536398",
    folder: "0047",
  },
  {
    id: "47b",
    name: "Minotaur",
    postUrl: "https://www.patreon.com/posts/47-minotaurs-19536398",
    folder: "047b",
  },
  {
    id: "48",
    name: "Barbarian (Axe)",
    postUrl: "https://www.patreon.com/posts/48-barbarian-2-19763850",
    folder: "0048",
  },
  {
    id: "48b",
    name: "Barbarian (Sword)",
    postUrl: "https://www.patreon.com/posts/48-barbarian-2-19763850",
    folder: "048b",
  },
  {
    id: "49",
    name: "Wererat Giant Rat",
    postUrl: "https://www.patreon.com/posts/49-50-51-wererat-20415574",
    folder: "0049",
  },
  {
    id: "50",
    name: "Wererat Hybrid",
    postUrl: "https://www.patreon.com/posts/49-50-51-wererat-20415574",
    folder: "0050",
  },
  {
    id: "51",
    name: "Wererat Humanoid",
    postUrl: "https://www.patreon.com/posts/49-50-51-wererat-20415574",
    folder: "0051",
  },
  {
    id: "52",
    name: "Werewolf Humanoid",
    postUrl: "https://www.patreon.com/posts/52-werewolf-form-20788219",
    folder: "0052",
  },
  {
    id: "53",
    name: "Werewolf Hybrid Free",
    postUrl: "https://www.patreon.com/posts/53-werewolf-form-20951158",
    folder: "0053",
  },
  {
    id: "54",
    name: "Wolf",
    postUrl: "https://www.patreon.com/posts/54-55-wolf-21135615",
    folder: "0054",
  },
  {
    id: "56",
    name: "Bear",
    postUrl: "https://www.patreon.com/posts/56-57-58-bears-21460503",
    folder: "0056",
  },
  {
    id: "58",
    name: "Werebear Humanoid",
    postUrl: "https://www.patreon.com/posts/56-57-58-bears-21460503",
    folder: "0058",
  },
  {
    id: "59",
    name: "Werebear Hybrid",
    postUrl: "https://www.patreon.com/posts/59-werebear-21728443",
    folder: "0059",
  },
  {
    id: "60",
    name: "WereTiger Humanoid",
    postUrl: "https://www.patreon.com/posts/60-weretiger-21922519",
    folder: "0060",
  },
  {
    id: "61",
    name: "Headless Horseman",
    postUrl: "https://www.patreon.com/posts/61-62-headless-22405495",
    folder: "0061",
  },
  {
    id: "62",
    name: "Flaming Horseman",
    postUrl: "https://www.patreon.com/posts/61-62-headless-22405495",
    folder: "0062",
  },
  {
    id: "63",
    name: "Kraken",
    postUrl: "https://www.patreon.com/posts/release-kraken-22702152",
    folder: "0063",
  },
  {
    id: "64",
    name: "Weretiger Hybrid",
    postUrl: "https://www.patreon.com/posts/64-weretiger-22859922",
    folder: "0064",
  },
  {
    id: "65",
    name: "Zombie 1",
    postUrl: "https://www.patreon.com/posts/65-66-pack-23092833",
    folder: "0065",
  },
  {
    id: "65b",
    name: "Zombie 1 Shiny",
    postUrl: "https://www.patreon.com/posts/65-66-pack-23092833",
    folder: "065b",
  },
  {
    id: "65c",
    name: "Zombie 2",
    postUrl: "https://www.patreon.com/posts/65-66-pack-23092833",
    folder: "065c",
  },
  {
    id: "65d",
    name: "Zombie 2 Shiny",
    postUrl: "https://www.patreon.com/posts/65-66-pack-23092833",
    folder: "065d",
  },
  {
    id: "65e",
    name: "Zombie 3",
    postUrl: "https://www.patreon.com/posts/65-66-pack-23092833",
    folder: "065e",
  },
  {
    id: "65f",
    name: "Zombie 3 Shiny",
    postUrl: "https://www.patreon.com/posts/65-66-pack-23092833",
    folder: "065f",
  },
  {
    id: "66",
    name: "Necromancer",
    postUrl: "https://www.patreon.com/posts/65-66-pack-23092833",
    folder: "0066",
  },
  {
    id: "67",
    name: "Tiger",
    postUrl: "https://www.patreon.com/posts/67-tiger-23385993",
    folder: "0067",
  },
  {
    id: "68",
    name: "Were Crocodile",
    postUrl: "https://www.patreon.com/posts/68-71-werecrocodile-24057085",
    folder: "0068",
  },
  {
    id: "70",
    name: "Crocodile",
    postUrl: "https://www.patreon.com/posts/70-crocodile-24142715",
    folder: "0070",
  },
  {
    id: "71",
    name: "Werecrocodile Humanoid",
    postUrl: "https://www.patreon.com/posts/71-werecrocodile-24142971",
    folder: "0071",
  },
  {
    id: "72",
    name: "Dragonborn Paladin",
    postUrl: "https://www.patreon.com/posts/72-dragonborn-24299072",
    folder: "0072",
  },
  {
    id: "73",
    name: "Dragonborn Ranger",
    postUrl: "https://www.patreon.com/posts/73-dragonborn-24476937",
    folder: "0073",
  },
  {
    id: "74",
    name: "Tiefling Sorceress",
    postUrl: "https://www.patreon.com/posts/74-tiefling-24640047",
    folder: "0074",
  },
  {
    id: "75",
    name: "Halfling Ranger",
    postUrl: "https://www.patreon.com/posts/halfling-ranger-24681493",
    folder: "0075",
  },
  {
    id: "76",
    name: "Half Orc Warrior",
    postUrl: "https://www.patreon.com/posts/76-half-orc-24964103",
    folder: "0076",
  },
  {
    id: "77a",
    name: "Forest Spirit (Horns)",
    postUrl: "https://www.patreon.com/posts/77-forest-spirit-25146221",
    folder: "077a",
  },
  {
    id: "77b",
    name: "Forest Spirit (Leafy)",
    postUrl: "https://www.patreon.com/posts/77-forest-spirit-25146221",
    folder: "077b",
  },
  {
    id: "77c",
    name: "Forest Spirit (Spirit)",
    postUrl: "https://www.patreon.com/posts/77-forest-spirit-25146221",
    folder: "077c",
  },
  {
    id: "77d",
    name: "Forest Spirit (Viney)",
    postUrl: "https://www.patreon.com/posts/77-forest-spirit-25146221",
    folder: "077d",
  },
  {
    id: "78",
    name: "Medusa",
    postUrl: "https://www.patreon.com/posts/78-medusa-25588193",
    folder: "0078",
  },
  {
    id: "82",
    name: "Clockwork Golem Pack",
    postUrl: "https://www.patreon.com/posts/82-clockwork-25953755",
    folder: "0082",
  },
  {
    id: "85",
    name: "Hydra",
    postUrl: "https://www.patreon.com/posts/85-hydra-26842819",
    folder: "0085",
  },
  {
    id: "96",
    name: "Harpy",
    postUrl:
      "https://www.paperforgeminis.com/minis/b8d97e41-93fa-4080-953c-1f621e231122",
    folder: "0096",
  },
  {
    id: "98",
    name: "Venom Crawler Hatchling",
    postUrl:
      "https://www.paperforgeminis.com/minis/f60957d6-7f45-49db-9087-5509998dd439",
    folder: "0098",
  },
  {
    id: "104",
    name: "Tavern Keeper",
    postUrl:
      "https://www.paperforgeminis.com/minis/895dad9b-d7de-46cc-a70d-6ab0e494eaba",
    folder: "0104",
  },
  {
    id: "106",
    name: "Tavern Maiden",
    postUrl:
      "https://www.paperforgeminis.com/minis/003b4e96-5b4d-4d30-ac48-6d44048852ed",
    folder: "0106",
  },
  {
    id: "112",
    name: "Townsman 1",
    postUrl:
      "https://www.paperforgeminis.com/minis/b16bed7a-aad9-440a-8e77-95f2bcc9a505",
    folder: "0112",
  },
  {
    id: "113",
    name: "Townsman 2",
    postUrl:
      "https://www.paperforgeminis.com/minis/b66345e0-0276-4405-bbfd-8e01265c9197",
    folder: "0113",
  },
  {
    id: "114",
    name: "Wing Sorceror",
    postUrl:
      "https://www.paperforgeminis.com/minis/0b2fc94d-dbdc-4601-b634-c2e0c08db715",
    folder: "0114",
  },
  {
    id: "116",
    name: "Drunken Townsman",
    postUrl:
      "https://www.paperforgeminis.com/minis/f5134e5d-e05c-448c-b014-b8218a537e6c",
    folder: "0116",
  },
  {
    id: "122",
    name: "Crone",
    postUrl:
      "https://www.paperforgeminis.com/minis/5cfcff78-2572-4b39-944c-9fe2a2e13705",
    folder: "0122",
  },
  {
    id: "123",
    name: "Vapul",
    postUrl:
      "https://www.paperforgeminis.com/minis/93700ff3-e8bf-4944-8861-88c69e8264d6",
    folder: "0123",
  },
  {
    id: "125",
    name: "Urchin Teen",
    postUrl:
      "https://www.paperforgeminis.com/minis/f3f39fa8-fdbf-4744-91f0-39ab5efdf3e4",
    folder: "0125",
  },
  {
    id: "126",
    name: "Urchin Kid",
    postUrl:
      "https://www.paperforgeminis.com/minis/6d8c2b25-bc5b-4473-baa1-3441d1572723",
    folder: "0126",
  },
  {
    id: "127",
    name: "Townswoman",
    postUrl:
      "https://www.paperforgeminis.com/minis/638618e3-9ae2-4295-b6fe-6a0502805b8a",
    folder: "0127",
  },
  {
    id: "128",
    name: "Cultist Hide",
    postUrl:
      "https://www.paperforgeminis.com/minis/512840df-d4c8-4437-8fba-fc735f06a35d",
    folder: "0128",
  },
  {
    id: "131",
    name: "Cultist Warlock",
    postUrl:
      "https://www.paperforgeminis.com/minis/10ee85e9-b640-48d2-a4ac-7b5badc8e951",
    folder: "0131",
  },
  {
    id: "140",
    name: "Chameleonfolk Warrior",
    postUrl:
      "https://www.paperforgeminis.com/minis/01e0b0ea-f62e-42b5-b724-4f54029baacd",
    folder: "0140",
  },
  {
    id: "141",
    name: "Chameleonfolk",
    postUrl:
      "https://www.paperforgeminis.com/minis/0acff80f-e44f-426e-8b57-223d43c011ef",
    folder: "0141",
  },
  {
    id: "155",
    name: "Rakshasa",
    postUrl:
      "https://www.paperforgeminis.com/minis/bcbb2742-8da6-40ae-a64a-81d87e8ba159",
    folder: "0155",
  },
  {
    id: "156",
    name: "Goblin Sorceror",
    postUrl:
      "https://www.paperforgeminis.com/minis/38d7834c-766f-49db-8c54-92cca83f1e8d",
    folder: "0156",
  },
  {
    id: "157",
    name: "Giant Scorpion",
    postUrl:
      "https://www.paperforgeminis.com/minis/800abe55-8cd6-4f93-b8a3-ea36074211de",
    folder: "0157",
  },
  {
    id: "158",
    name: "Bullywug",
    postUrl:
      "https://www.paperforgeminis.com/minis/1dda0479-13df-471e-9b3e-d71bdaadebd4",
    folder: "0158",
  },
  {
    id: "160",
    name: "Bullywug Queen",
    postUrl:
      "https://www.paperforgeminis.com/minis/83c11b70-326a-4df2-b93a-69929ebd84be",
    folder: "0160",
  },
  {
    id: "161",
    name: "Bugbear",
    postUrl:
      "https://www.paperforgeminis.com/minis/91849fba-f8b0-417d-9ccb-97a5b125341f",
    folder: "0161",
  },
  {
    id: "162",
    name: "Otyugh",
    postUrl:
      "https://www.paperforgeminis.com/minis/663b8cca-52c5-4458-8f5f-bb748fd69993",
    folder: "0162",
  },
  {
    id: "163",
    name: "Giant Centipede",
    postUrl:
      "https://www.paperforgeminis.com/minis/2d6d1da6-376d-420e-b87b-8375734f9fe7",
    folder: "0163",
  },
  {
    id: "164",
    name: "Ogre",
    postUrl:
      "https://www.paperforgeminis.com/minis/179c4543-1efd-4532-875d-50a5fa058065",
    folder: "0164",
  },
  {
    id: "165",
    name: "Tiefling Warlock",
    postUrl:
      "https://www.paperforgeminis.com/minis/c6fc61c7-d0d1-4517-976f-6c800d6d4e6a",
    folder: "0165",
  },
  {
    id: "166",
    name: "Sleuth",
    postUrl:
      "https://www.paperforgeminis.com/minis/59c3e831-42ef-4fdf-9d30-eccee2d8538c",
    folder: "0166",
  },
  {
    id: "167",
    name: "Operative",
    postUrl:
      "https://www.paperforgeminis.com/minis/99c739bc-dadf-4f63-b494-766cc3136fc2",
    folder: "0167",
  },
  {
    id: "168",
    name: "Spectral Agent",
    postUrl:
      "https://www.paperforgeminis.com/minis/642ca72f-b5b8-44cc-b228-3019b7535396",
    folder: "0168",
  },
  {
    id: "170",
    name: "Half Orc Paladin",
    postUrl:
      "https://www.paperforgeminis.com/minis/bc07add5-9d0b-4f6a-b735-238d88ab8a0d",
    folder: "0170",
  },
  {
    id: "171",
    name: "Paladin",
    postUrl:
      "https://www.paperforgeminis.com/minis/7db27e28-b480-489a-8cbc-df96ead19ed1",
    folder: "0171",
  },
  {
    id: "173",
    name: "Chempunk Ogre",
    postUrl:
      "https://www.paperforgeminis.com/minis/ed7646ae-d0b2-4fda-94a0-bffc0b6cebff",
    folder: "0173",
  },
  {
    id: "174",
    name: "Chempunk Scientist",
    postUrl:
      "https://www.paperforgeminis.com/minis/9d21bc87-e5f0-4f24-8aa5-11381dd52351",
    folder: "0174",
  },
  {
    id: "175",
    name: "Chempunk Hose",
    postUrl:
      "https://www.paperforgeminis.com/minis/30dbe66d-bfa5-4973-b03c-58849b08ec31",
    folder: "0175",
  },
  {
    id: "176",
    name: "Skeleton",
    postUrl:
      "https://www.paperforgeminis.com/minis/1884960c-ace7-479b-a699-82d01ae45f07",
    folder: "0176",
  },
  {
    id: "177",
    name: "Skeleton Archer",
    postUrl:
      "https://www.paperforgeminis.com/minis/410c2abb-4274-48b8-a2f2-bdab2031e205",
    folder: "0177",
  },
  {
    id: "178",
    name: "Skeleton Rogue",
    postUrl:
      "https://www.paperforgeminis.com/minis/8c7716ae-ad6c-4068-afd7-4d17b075d764",
    folder: "0178",
  },
  {
    id: "179",
    name: "Skeleton Spearman",
    postUrl:
      "https://www.paperforgeminis.com/minis/b276e30a-5f75-4d4c-ae42-013ad400ccc7",
    folder: "0179",
  },
  {
    id: "180",
    name: "Skeleton Warrior",
    postUrl:
      "https://www.paperforgeminis.com/minis/8f3a0027-f477-4fe5-8627-ace1bf2503b6",
    folder: "0180",
  },
  {
    id: "185",
    name: "Troll",
    postUrl:
      "https://www.paperforgeminis.com/minis/9211e241-5f2b-466d-8820-a45e08a7edb1",
    folder: "0185",
  },
  {
    id: "187",
    name: "Orc Warrior",
    postUrl:
      "https://www.paperforgeminis.com/minis/ff5d148b-4c43-4a37-9e75-833a0d8927c8",
    folder: "0187",
  },
  {
    id: "188",
    name: "Orc Swordsman",
    postUrl:
      "https://www.paperforgeminis.com/minis/e1c6fce2-0bd1-4920-9b23-2db03cdb6109",
    folder: "0188",
  },
  {
    id: "189",
    name: "Orc Spearman",
    postUrl:
      "https://www.paperforgeminis.com/minis/3469177f-5e10-4dc2-848f-67f65794bb02",
    folder: "0189",
  },
  {
    id: "192",
    name: "Cat",
    postUrl:
      "https://www.paperforgeminis.com/minis/b68d4d16-f6f2-47f2-a471-5862a4fc7f8f",
    folder: "0192",
  },
  {
    id: "195",
    name: "Weasel",
    postUrl:
      "https://www.paperforgeminis.com/minis/cdc05c2e-e5bf-4e44-929d-abbec24e022b",
    folder: "0195",
  },
  {
    id: "196",
    name: "Swarm of Centipedes",
    postUrl:
      "https://www.paperforgeminis.com/minis/d101c1f5-eb78-4dc6-a3e3-b7dad6f7ec04",
    folder: "0196",
  },
  {
    id: "197",
    name: "Threndl Keeper",
    postUrl:
      "https://www.paperforgeminis.com/minis/5e5f3e0f-5315-410d-800f-d92ade4820ac",
    folder: "0197",
  },
  {
    id: "198",
    name: "Threndl Scout",
    postUrl:
      "https://www.paperforgeminis.com/minis/57326751-2243-4326-b396-2e0b9b1069c3",
    folder: "0198",
  },
  {
    id: "200",
    name: "Female Satyr",
    postUrl:
      "https://www.paperforgeminis.com/minis/e53a7e74-2f9c-4fb0-a912-33178f28730b",
    folder: "0200",
  },
  {
    id: "201",
    name: "Satyr",
    postUrl:
      "https://www.paperforgeminis.com/minis/2caa0320-87d5-4ddd-b452-262a2c3dd0b4",
    folder: "0201",
  },
  {
    id: "202",
    name: "Satyr Bard Fem",
    postUrl:
      "https://www.paperforgeminis.com/minis/4f42ec56-196b-4647-b0d6-1d4f42b8c161",
    folder: "0202",
  },
  {
    id: "203",
    name: "Satyr Bard",
    postUrl:
      "https://www.paperforgeminis.com/minis/1f542536-2d59-4b5e-9e9e-a64059f735a0",
    folder: "0203",
  },
  {
    id: "204",
    name: "Satyr Warrior Fem",
    postUrl:
      "https://www.paperforgeminis.com/minis/5507eb7b-b8bc-4af7-ad0c-9e6f280c26a8",
    folder: "0204",
  },
  {
    id: "205",
    name: "Satyr Warrior",
    postUrl:
      "https://www.paperforgeminis.com/minis/c875cfc0-4c4f-4fa7-8ce1-57755d8ffd93",
    folder: "0205",
  },
  {
    id: "211",
    name: "Owl",
    postUrl:
      "https://www.paperforgeminis.com/minis/0ac406b3-12f0-4d3c-b20b-0293c94e3c6c",
    folder: "0211",
  },
  {
    id: "212",
    name: "Eldritch Cannon",
    postUrl:
      "https://www.paperforgeminis.com/minis/531fb1fa-2a03-4c8b-b3d1-92ba9f659adc",
    folder: "0212",
  },
  {
    id: "214",
    name: "Mechanical Homunculus",
    postUrl:
      "https://www.paperforgeminis.com/minis/3504ac67-ba7f-4262-a6eb-d5804cd481f3",
    folder: "0214",
  },
  {
    id: "216",
    name: "Lizardfolk",
    postUrl:
      "https://www.paperforgeminis.com/minis/e30ed4bc-5c02-4ca3-bab0-110822c08657",
    folder: "0216",
  },
  {
    id: "217",
    name: "Lizardfolk Warrior",
    postUrl:
      "https://www.paperforgeminis.com/minis/63de9107-2fe3-4a00-8178-8595852752f4",
    folder: "0217",
  },
  {
    id: "219",
    name: "Pale Outlaw",
    postUrl:
      "https://www.paperforgeminis.com/minis/67313e21-81a5-4804-b942-b0ddaef6425d",
    folder: "0219",
  },
  {
    id: "220",
    name: "Animated Revolver",
    postUrl:
      "https://www.paperforgeminis.com/minis/745d52bc-86d4-4c29-a66e-e6bbe9af6a74",
    folder: "0220",
  },
  {
    id: "221",
    name: "Terror Weed",
    postUrl:
      "https://www.paperforgeminis.com/minis/d878d7da-098f-418e-adfd-316cd4de5b39",
    folder: "0221",
  },
  {
    id: "223",
    name: "Dwarf Barbarian",
    postUrl:
      "https://www.paperforgeminis.com/minis/506aad3e-5d77-41ab-b268-f3cf9c33e2f4",
    folder: "0223",
  },
  {
    id: "224",
    name: "Dwarf Barbarian ",
    postUrl:
      "https://www.paperforgeminis.com/minis/dcf5fdb4-b956-4d9a-aa27-2652fbbd6c0f",
    folder: "0224",
  },
  {
    id: "225",
    name: "Dwarf Paladin ",
    postUrl:
      "https://www.paperforgeminis.com/minis/5576305d-bc2c-4f38-9003-03af417215c5",
    folder: "0225",
  },
  {
    id: "226",
    name: "Dwarf Paladin ",
    postUrl:
      "https://www.paperforgeminis.com/minis/90659bc3-075e-47c0-adbb-0b22c59ba9fa",
    folder: "0226",
  },
  {
    id: "227",
    name: "Dwarf Cleric",
    postUrl:
      "https://www.paperforgeminis.com/minis/bc4929c2-f1d3-4dd0-917e-1690668bdba1",
    folder: "0227",
  },
  {
    id: "228",
    name: "Dwarf Cleric",
    postUrl:
      "https://www.paperforgeminis.com/minis/0420e726-fb3f-4e9e-a960-b872ed38fe5c",
    folder: "0228",
  },
  {
    id: "229",
    name: "Bear",
    postUrl:
      "https://www.paperforgeminis.com/minis/c4ab26aa-e4a6-4ac6-b486-2bdbc6293023",
    folder: "0229",
  },
  {
    id: "232",
    name: "Ghoul",
    postUrl:
      "https://www.paperforgeminis.com/minis/d0875ac1-4b59-464b-960e-47df39c47a83",
    folder: "0232",
  },
  {
    id: "233",
    name: "Crawling Hand",
    postUrl:
      "https://www.paperforgeminis.com/minis/528df40d-c88d-48fb-aba6-32f27ea9405d",
    folder: "0233",
  },
  {
    id: "234",
    name: "Goblin Alchemist",
    postUrl:
      "https://www.paperforgeminis.com/minis/2ea12d48-b8f7-4bad-a995-f89e820e30ce",
    folder: "0234",
  },
  {
    id: "235",
    name: "Giant Fire Beetle",
    postUrl:
      "https://www.paperforgeminis.com/minis/559ce208-9aa0-49d1-84f9-3b4d732b1427",
    folder: "0235",
  },
  {
    id: "238",
    name: "Monk",
    postUrl:
      "https://www.paperforgeminis.com/minis/67f27941-a8a6-4fe6-87fa-fc4bd0fe6227",
    folder: "0238",
  },
  {
    id: "239",
    name: "Flying Hammer",
    postUrl:
      "https://www.paperforgeminis.com/minis/402bd678-a73a-4eff-9480-7662c23755e8",
    folder: "0239",
  },
  {
    id: "242",
    name: "Flying Sword",
    postUrl:
      "https://www.paperforgeminis.com/minis/fa67e0bf-65a2-458a-9bfc-f440caec44df",
    folder: "0242",
  },
  {
    id: "243",
    name: "Animated Voodoo Doll",
    postUrl:
      "https://www.paperforgeminis.com/minis/e281c778-a311-4892-9b53-4fdeaac4ac43",
    folder: "0243",
  },
  {
    id: "244",
    name: "Giant Frog",
    postUrl:
      "https://www.paperforgeminis.com/minis/4cc2669e-202e-4c1a-bf58-ed836dd70daf",
    folder: "0244",
  },
  {
    id: "245",
    name: "Monk",
    postUrl:
      "https://www.paperforgeminis.com/minis/7cbe28ea-9a06-46a6-9d6f-28de95669767",
    folder: "0245",
  },
  {
    id: "247",
    name: "Human Sorceress",
    postUrl:
      "https://www.paperforgeminis.com/minis/97a2d089-5031-4125-8ddc-db29e86340c3",
    folder: "0247",
  },
  {
    id: "248",
    name: "Elf Warrior",
    postUrl:
      "https://www.paperforgeminis.com/minis/d767ebe8-6df7-4818-bbc3-860a7e0f0ceb",
    folder: "0248",
  },
  {
    id: "250",
    name: "Snow Golem",
    postUrl:
      "https://www.paperforgeminis.com/minis/c1062b36-590c-4eff-bfd0-5e4b54a913da",
    folder: "0250",
  },
  {
    id: "252",
    name: "Pumpkin Harvester",
    postUrl:
      "https://www.paperforgeminis.com/minis/5f961afe-a578-4d31-ad94-92591d5725fe",
    folder: "0252",
  },
  {
    id: "253",
    name: "Skeletal Mage",
    postUrl:
      "https://www.paperforgeminis.com/minis/b39e4a1a-d977-4831-b63e-95eb22fd3668",
    folder: "0253",
  },
  {
    id: "254",
    name: "FlameSkull",
    postUrl:
      "https://www.paperforgeminis.com/minis/2159d481-a7dd-4ed9-b39c-67860b8e6358",
    folder: "0254",
  },
  {
    id: "255",
    name: "Ghast",
    postUrl:
      "https://www.paperforgeminis.com/minis/b4808d30-eda6-492e-8bab-1121dae7dfeb",
    folder: "0255",
  },
  {
    id: "256",
    name: " Gnome Bard",
    postUrl:
      "https://www.paperforgeminis.com/minis/a1d18cf9-002a-4755-8f7f-d2022fdead70",
    folder: "0256",
  },
  {
    id: "258",
    name: "Bandit",
    postUrl:
      "https://www.paperforgeminis.com/minis/cc673f3b-aedf-4cc2-ad39-c4382b208574",
    folder: "0258",
  },
  {
    id: "259",
    name: "Bandit",
    postUrl:
      "https://www.paperforgeminis.com/minis/44d1cf7b-4897-423e-b61c-5b81c9fd4188",
    folder: "0259",
  },
  {
    id: "260",
    name: "Human Rogue",
    postUrl:
      "https://www.paperforgeminis.com/minis/931e5d54-bad2-405a-955a-6e5df78c63ef",
    folder: "0260",
  },
  {
    id: "261",
    name: "Loxodon Wizard",
    postUrl:
      "https://www.paperforgeminis.com/minis/e1784b91-dcfc-4089-b3b5-9342836b1044",
    folder: "0261",
  },
  {
    id: "262",
    name: "Loxodon Druid",
    postUrl:
      "https://www.paperforgeminis.com/minis/cb7f0569-a7ac-4015-b3be-b9abf6ef6bc0",
    folder: "0262",
  },
  {
    id: "264",
    name: "Tiefling Paladin",
    postUrl:
      "https://www.paperforgeminis.com/minis/5bca5ed1-2771-4b63-829a-a81b412b52f0",
    folder: "0264",
  },
  {
    id: "265",
    name: "Tiefling Paladin",
    postUrl:
      "https://www.paperforgeminis.com/minis/8ba0efa9-e8b8-427c-8a0c-459ca31acd4e",
    folder: "0265",
  },
  {
    id: "266",
    name: "Ranger",
    postUrl:
      "https://www.paperforgeminis.com/minis/dba94d9c-df9e-4766-886d-1b676dbc0500",
    folder: "0266",
  },
  {
    id: "268",
    name: "Tiefling Ranger",
    postUrl:
      "https://www.paperforgeminis.com/minis/2b145c9c-e8e3-411f-bdde-9414ebe25718",
    folder: "0268",
  },
  {
    id: "270",
    name: "Wizard",
    postUrl:
      "https://www.paperforgeminis.com/minis/782352ee-6395-425d-8d09-f6fecb52eb37",
    folder: "0270",
  },
  {
    id: "271",
    name: "Tiefling Wizard",
    postUrl:
      "https://www.paperforgeminis.com/minis/045b530a-547c-4551-b4c2-c07370f11e27",
    folder: "0271",
  },
  {
    id: "273",
    name: "Dragonborn Wizard",
    postUrl:
      "https://www.paperforgeminis.com/minis/9a204b00-6c98-4bdb-9884-73596b1d17f4",
    folder: "0273",
  },
  {
    id: "274",
    name: "Dwarf Warrior",
    postUrl:
      "https://www.paperforgeminis.com/minis/fc8ab882-0171-4ba4-95f1-1fce13dcfda5",
    folder: "0274",
  },
  {
    id: "275",
    name: "Flying Dagger",
    postUrl:
      "https://www.paperforgeminis.com/minis/6ea44e4f-6b2e-4e80-ac01-8d303c3afa26",
    folder: "0275",
  },
  {
    id: "277",
    name: "Specter",
    postUrl:
      "https://www.paperforgeminis.com/minis/633da828-1720-444b-8a21-725166a7dc24",
    folder: "0277",
  },
  {
    id: "278",
    name: "Wraith",
    postUrl:
      "https://www.paperforgeminis.com/minis/80e05b38-8025-4312-a254-bf3fde811edb",
    folder: "0278",
  },
  {
    id: "280",
    name: "Charon Ferryman",
    postUrl:
      "https://www.paperforgeminis.com/minis/ca3301f4-0c4a-464e-9c03-ec2e55614663",
    folder: "0280",
  },
  {
    id: "281",
    name: "Charon",
    postUrl:
      "https://www.paperforgeminis.com/minis/d0f99ac6-2485-4e48-9df6-eb61926a18be",
    folder: "0281",
  },
  {
    id: "282",
    name: "Charon's Ferry",
    postUrl:
      "https://www.paperforgeminis.com/minis/5df116f3-4073-46d7-89e0-3dac74328170",
    folder: "0282",
  },
  {
    id: "283",
    name: "Styxian Soul",
    postUrl:
      "https://www.paperforgeminis.com/minis/f06b68f8-1216-4b1d-8924-c3005e707130",
    folder: "0283",
  },
  {
    id: "284",
    name: "Floating Ember",
    postUrl:
      "https://www.paperforgeminis.com/minis/825b8fb7-3b61-4b62-9768-0457b6352422",
    folder: "0284",
  },
  {
    id: "285",
    name: "Boar",
    postUrl:
      "https://www.paperforgeminis.com/minis/07d5f224-1e0b-488d-80b6-69212bee3da0",
    folder: "0285",
  },
  {
    id: "286",
    name: "Boarlet",
    postUrl:
      "https://www.paperforgeminis.com/minis/f85668f7-11a2-4ee6-b380-aecb4ae7b202",
    folder: "0286",
  },
  {
    id: "287",
    name: "Boar",
    postUrl:
      "https://www.paperforgeminis.com/minis/cf3ee246-f77c-428b-9827-4e05109c4e89",
    folder: "0287",
  },
  {
    id: "289",
    name: "Pseudo Dragon",
    postUrl:
      "https://www.paperforgeminis.com/minis/d9206c98-fcbe-421c-9d6f-87124281b06e",
    folder: "0289",
  },
  {
    id: "291",
    name: "Gnome Artificer",
    postUrl:
      "https://www.paperforgeminis.com/minis/1f73e743-b036-4396-aa48-2a522a20c6e2",
    folder: "0291",
  },
  {
    id: "292",
    name: "Halfling Druid",
    postUrl:
      "https://www.paperforgeminis.com/minis/e7c7caac-8893-4fa6-b746-482a291f1153",
    folder: "0292",
  },
  {
    id: "293",
    name: "Tabaxi Monk",
    postUrl:
      "https://www.paperforgeminis.com/minis/ac626657-1002-42f4-9695-514b1e5e387e",
    folder: "0293",
  },
  {
    id: "294",
    name: "Tabaxi Rogue",
    postUrl:
      "https://www.paperforgeminis.com/minis/9324b6dc-1ec0-4e94-82a2-e2b2f3a04486",
    folder: "0294",
  },
  {
    id: "296",
    name: "Tabaxi Monk",
    postUrl:
      "https://www.paperforgeminis.com/minis/12a36df1-cd0b-4922-a66a-be14cb1c42c7",
    folder: "0296",
  },
  {
    id: "297",
    name: "Crelid",
    postUrl:
      "https://www.paperforgeminis.com/minis/01532194-5877-4071-8426-17da40706ac9",
    folder: "0297",
  },
  {
    id: "299",
    name: "Cultist Fang",
    postUrl:
      "https://www.paperforgeminis.com/minis/100441b2-d6c8-4857-8ff4-2d40dedc381a",
    folder: "0299",
  },
  {
    id: "300",
    name: "Cult Assassin",
    postUrl:
      "https://www.paperforgeminis.com/minis/13784ebf-58b3-4a02-bcb1-ccae219e04d7",
    folder: "0300",
  },
  {
    id: "301",
    name: "Halfling Monk",
    postUrl:
      "https://www.paperforgeminis.com/minis/bea6ec8c-24d8-4f43-9e4b-6baef959a12a",
    folder: "0301",
  },
  {
    id: "302",
    name: "Cultist Wing",
    postUrl:
      "https://www.paperforgeminis.com/minis/1f76651d-f40b-41c9-a997-f3daeaaa38fd",
    folder: "0302",
  },
  {
    id: "304",
    name: "Town Guard",
    postUrl:
      "https://www.paperforgeminis.com/minis/7719f1b9-e73d-432c-878a-075c5c372d5a",
    folder: "0304",
  },
  {
    id: "305",
    name: "Town Guard",
    postUrl:
      "https://www.paperforgeminis.com/minis/ffada08f-175b-47e1-84c9-fa29a0986ea0",
    folder: "0305",
  },
  {
    id: "306",
    name: "Town Guard",
    postUrl:
      "https://www.paperforgeminis.com/minis/4b4953ca-0ca1-46f5-a1a4-20db954d3458",
    folder: "0306",
  },
  {
    id: "307",
    name: "Town Guard",
    postUrl:
      "https://www.paperforgeminis.com/minis/69e6ce0e-7e88-4c4a-abe2-7e8fbd521c4d",
    folder: "0307",
  },
  {
    id: "308",
    name: "Town Guard",
    postUrl:
      "https://www.paperforgeminis.com/minis/f18e6f4e-56bb-482f-a99b-919394c0251b",
    folder: "0308",
  },
  {
    id: "309",
    name: "Town Guard",
    postUrl:
      "https://www.paperforgeminis.com/minis/973a387c-4cb8-47b6-9774-00e6297dbf17",
    folder: "0309",
  },
  {
    id: "310",
    name: "Town Guard",
    postUrl:
      "https://www.paperforgeminis.com/minis/21e4f456-3943-484b-831f-7771e727ca06",
    folder: "0310",
  },
  {
    id: "311",
    name: "Town Guard",
    postUrl:
      "https://www.paperforgeminis.com/minis/d7f6fe0a-090a-43e3-bf1e-f32f0947462c",
    folder: "0311",
  },
  {
    id: "312",
    name: "Town Guard Captain",
    postUrl:
      "https://www.paperforgeminis.com/minis/bddb124b-3ed4-4774-bb2d-552d6f7969a0",
    folder: "0312",
  },
  {
    id: "313",
    name: "Town Guard Captain",
    postUrl:
      "https://www.paperforgeminis.com/minis/a9ae2522-5977-49e9-9674-abe0d7b03ee2",
    folder: "0313",
  },
  {
    id: "319",
    name: "Pirate Crew Member",
    postUrl:
      "https://www.paperforgeminis.com/minis/b9ee7854-4506-4dc2-a597-fe3751ecccb8",
    folder: "0319",
  },
  {
    id: "320",
    name: "Pirate Crew Member",
    postUrl:
      "https://www.paperforgeminis.com/minis/9a9de3e5-5fbb-4a1b-92b0-a7dd6980c9ce",
    folder: "0320",
  },
  {
    id: "321",
    name: "Pirate Crew Member",
    postUrl:
      "https://www.paperforgeminis.com/minis/331125e3-2e57-4e10-a195-021b508abd64",
    folder: "0321",
  },
  {
    id: "322",
    name: "Pirate Crew Member",
    postUrl:
      "https://www.paperforgeminis.com/minis/d3ec6031-a5d5-417e-8c08-dcd813da4fbb",
    folder: "0322",
  },
  {
    id: "323",
    name: "Depth Watcher",
    postUrl:
      "https://www.paperforgeminis.com/minis/e86d3577-5a4c-41f9-93b2-6191190b50a5",
    folder: "0323",
  },
  {
    id: "324",
    name: "Pirate Crew Member",
    postUrl:
      "https://www.paperforgeminis.com/minis/87c4d7ae-17e1-4e68-8873-fcc1b1408813",
    folder: "0324",
  },
  {
    id: "325",
    name: "Pirate Captain",
    postUrl:
      "https://www.paperforgeminis.com/minis/99744ed2-1c42-451a-b838-8c3366d16784",
    folder: "0325",
  },
  {
    id: "326",
    name: "Pirate Crew Member",
    postUrl:
      "https://www.paperforgeminis.com/minis/75976d4c-7b15-4eaa-a262-eabaed2bae73",
    folder: "0326",
  },
  {
    id: "327",
    name: "Pirate Crew Member",
    postUrl:
      "https://www.paperforgeminis.com/minis/12c5c24b-6de5-4a94-8687-05648929cc1b",
    folder: "0327",
  },
  {
    id: "328",
    name: "Pirate Crew Member",
    postUrl:
      "https://www.paperforgeminis.com/minis/11e65a0d-09cb-4cc7-8d1d-8cf23149f78b",
    folder: "0328",
  },
  {
    id: "329",
    name: "Pirate Captain",
    postUrl:
      "https://www.paperforgeminis.com/minis/1fac8dc2-8c25-46f4-b75c-f4e8da77e471",
    folder: "0329",
  },
  {
    id: "330",
    name: "Monkey",
    postUrl:
      "https://www.paperforgeminis.com/minis/c837757e-b715-4037-8929-0e5fed3b9397",
    folder: "0330",
  },
  {
    id: "332",
    name: "Parrot",
    postUrl:
      "https://www.paperforgeminis.com/minis/e65bc081-3554-49e5-a355-a1b250b64155",
    folder: "0332",
  },
  {
    id: "340",
    name: "Intellect Devourer",
    postUrl:
      "https://www.paperforgeminis.com/minis/cc64854a-c245-430c-8ee7-a48a249a375f",
    folder: "0340",
  },
  {
    id: "341",
    name: "Intellect Devourer",
    postUrl:
      "https://www.paperforgeminis.com/minis/c0e9c3c3-044c-4bf3-9b8b-1ebaebdb17ae",
    folder: "0341",
  },
  {
    id: "342",
    name: "Gnome Ceremorph",
    postUrl:
      "https://www.paperforgeminis.com/minis/d120c58f-e1a0-44fc-a72d-32ae1df0ef84",
    folder: "0342",
  },
  {
    id: "343",
    name: "Gnome Ceremorph",
    postUrl:
      "https://www.paperforgeminis.com/minis/d9da2266-4fa4-49f3-8384-4f9a2ee59e1b",
    folder: "0343",
  },
  {
    id: "344",
    name: "Gnome Squidling",
    postUrl:
      "https://www.paperforgeminis.com/minis/31c1cf33-3166-4b86-9b94-6ccd683e1f78",
    folder: "0344",
  },
  {
    id: "345",
    name: "Potions Merchant",
    postUrl:
      "https://www.paperforgeminis.com/minis/0bb69ee7-7846-43d6-bbc1-9003ca8ba34c",
    folder: "0345",
  },
  {
    id: "348",
    name: "Mind Flayer",
    postUrl:
      "https://www.paperforgeminis.com/minis/34d6b437-8a65-44fb-a25d-eeb4a41ed717",
    folder: "0348",
  },
  {
    id: "349",
    name: "Mind Flayer",
    postUrl:
      "https://www.paperforgeminis.com/minis/75bf550c-d1ca-4ebf-92c9-614c142ad5ed",
    folder: "0349",
  },
  {
    id: "350",
    name: "DarkMantle",
    postUrl:
      "https://www.paperforgeminis.com/minis/f21458d7-884f-406d-b552-25a396a8a7a3",
    folder: "0350",
  },
  {
    id: "352",
    name: "Griffon",
    postUrl:
      "https://www.paperforgeminis.com/minis/57bbb8c1-b2e2-4afb-ad14-1bfdfc863b19",
    folder: "0352",
  },
  {
    id: "353",
    name: "Griffon Fledgling",
    postUrl:
      "https://www.paperforgeminis.com/minis/3678deb1-3dad-4ec2-9b53-afe01f3741c5",
    folder: "0353",
  },
  {
    id: "354",
    name: "Griffon Fledgling",
    postUrl:
      "https://www.paperforgeminis.com/minis/f3e19120-80e9-4fc8-a53f-f92d47701b72",
    folder: "0354",
  },
  {
    id: "357",
    name: "Halfling Bard ",
    postUrl:
      "https://www.paperforgeminis.com/minis/cc1ca782-743e-4971-9dd1-c4622647c811",
    folder: "0357",
  },
  {
    id: "358",
    name: "Halfling Wizard",
    postUrl:
      "https://www.paperforgeminis.com/minis/b56ec8dd-e7ca-44c1-8c8d-7fe6fdfd74c9",
    folder: "0358",
  },
  {
    id: "360",
    name: "Gnome Paladin",
    postUrl:
      "https://www.paperforgeminis.com/minis/b76773b0-a887-439f-9192-c6f588e0354a",
    folder: "0360",
  },
  {
    id: "362",
    name: "Homunculus",
    postUrl:
      "https://www.paperforgeminis.com/minis/79b52dcc-eb30-4286-a093-630696d406ac",
    folder: "0362",
  },
  {
    id: "364",
    name: "Forgework Dragon",
    postUrl:
      "https://www.paperforgeminis.com/minis/859d588b-f57b-4450-bf24-f399ada1e670",
    folder: "0364",
  },
  {
    id: "365",
    name: "Forgework Dragon Wyrmling",
    postUrl:
      "https://www.paperforgeminis.com/minis/53f6a170-b74f-40c6-8bad-f35229157b58",
    folder: "0365",
  },
  {
    id: "367",
    name: "Half Ogre",
    postUrl:
      "https://www.paperforgeminis.com/minis/b02edf32-a8b8-4c9c-aa8c-c5c74ed1a351",
    folder: "0367",
  },
  {
    id: "369",
    name: "Hobgoblin Soldier",
    postUrl:
      "https://www.paperforgeminis.com/minis/598daa0b-5522-453b-9667-70840111d7e4",
    folder: "0369",
  },
  {
    id: "370",
    name: "Doppleganger",
    postUrl:
      "https://www.paperforgeminis.com/minis/035ef704-9d49-4ec1-bc22-a54a3eb32b7d",
    folder: "0370",
  },
  {
    id: "378",
    name: "Fire Genasi",
    postUrl:
      "https://www.paperforgeminis.com/minis/d5b06f30-931b-40e6-96d5-2829107304a5",
    folder: "0378",
  },
  {
    id: "379",
    name: "Fire Genasi Wizard",
    postUrl:
      "https://www.paperforgeminis.com/minis/2d18b756-d657-4b61-b0d6-ae9475c346d7",
    folder: "0379",
  },
  {
    id: "381",
    name: "Fire Genasi Fem",
    postUrl:
      "https://www.paperforgeminis.com/minis/abc94719-a0cf-4784-b7c0-c44fa86eee9c",
    folder: "0381",
  },
  {
    id: "382",
    name: "Fire Genasi Wizard Fem",
    postUrl:
      "https://www.paperforgeminis.com/minis/6a63a474-35ee-4b90-9d54-b17516ea24e1",
    folder: "0382",
  },
  {
    id: "385",
    name: "Fairy Sorceress",
    postUrl:
      "https://www.paperforgeminis.com/minis/3c487465-f9bc-44e7-8e00-3f265a8020a8",
    folder: "0385",
  },
  {
    id: "386",
    name: "Fairy Warrior",
    postUrl:
      "https://www.paperforgeminis.com/minis/a0039660-511c-40a1-b6ee-b2148c44c322",
    folder: "0386",
  },
  {
    id: "388",
    name: "Fairy Mage",
    postUrl:
      "https://www.paperforgeminis.com/minis/333f5041-38ff-4264-8aff-32f6fb7b63f8",
    folder: "0388",
  },
  {
    id: "390",
    name: "Yeti",
    postUrl:
      "https://www.paperforgeminis.com/minis/daf1afbf-057e-4805-b4b2-1762e3d2af6a",
    folder: "0390",
  },
  {
    id: "391",
    name: "Baby Yeti",
    postUrl:
      "https://www.paperforgeminis.com/minis/43500896-2a44-444c-b926-d59ed7bf9a11",
    folder: "0391",
  },
  {
    id: "393",
    name: "Flail Snail",
    postUrl:
      "https://www.paperforgeminis.com/minis/a09086ef-5531-4892-b538-b2bc7280671c",
    folder: "0393",
  },
  {
    id: "395",
    name: "Boggle",
    postUrl:
      "https://www.paperforgeminis.com/minis/ba4f910b-09ab-465e-9272-379bfc262f5e",
    folder: "0395",
  },
  {
    id: "396",
    name: "Hobgoblin Devastator",
    postUrl:
      "https://www.paperforgeminis.com/minis/ca42f43a-b44c-400d-8b8c-0921e5d003db",
    folder: "0396",
  },
  {
    id: "398",
    name: "Bodak",
    postUrl:
      "https://www.paperforgeminis.com/minis/f20cc412-1861-4caf-bea5-f3c167c84d8f",
    folder: "0398",
  },
  {
    id: "400",
    name: "Human Warrior",
    postUrl:
      "https://www.paperforgeminis.com/minis/5dd4cef9-20c6-42a0-a009-22409063277a",
    folder: "0400",
  },
  {
    id: "402",
    name: "Cave Fisher",
    postUrl:
      "https://www.paperforgeminis.com/minis/249db8f8-6980-4b7f-b703-0a2ad08f09d6",
    folder: "0402",
  },
  {
    id: "404",
    name: "Human Fighter",
    postUrl:
      "https://www.paperforgeminis.com/minis/40cb406b-b1cf-4fb0-808d-e807c45e8da2",
    folder: "0404",
  },
  {
    id: "405",
    name: "Vargouille",
    postUrl:
      "https://www.paperforgeminis.com/minis/1bba6fa2-57fb-4987-b1e0-4a6cc19835b7",
    folder: "0405",
  },
  {
    id: "406",
    name: "Kirin",
    postUrl:
      "https://www.paperforgeminis.com/minis/253f3548-17cd-48c8-8374-c6921c245dc4",
    folder: "0406",
  },
  {
    id: "407",
    name: "Zombie ",
    postUrl:
      "https://www.paperforgeminis.com/minis/58742da8-b2b7-4414-a97d-335bd7bfa137",
    folder: "0407",
  },
  {
    id: "408",
    name: "Vargouille ",
    postUrl:
      "https://www.paperforgeminis.com/minis/b8d50fa3-a578-410c-84df-cd468f536cab",
    folder: "0408",
  },
  {
    id: "409",
    name: "Devourer",
    postUrl:
      "https://www.paperforgeminis.com/minis/bd50b8b2-51a6-4aed-bd4e-212ed23e4d7a",
    folder: "0409",
  },
  {
    id: "410",
    name: "Devourer Empty",
    postUrl:
      "https://www.paperforgeminis.com/minis/eb587b36-3b63-4559-9dd9-9cdc2bfdf402",
    folder: "0410",
  },
  {
    id: "411",
    name: "Zombie",
    postUrl:
      "https://www.paperforgeminis.com/minis/5e384346-6bd0-4a20-bf30-84e54c670125",
    folder: "0411",
  },
  {
    id: "412",
    name: "Vargouille",
    postUrl:
      "https://www.paperforgeminis.com/minis/759e01ea-fd52-4b0d-bfc5-1059b5717719",
    folder: "0412",
  },
  {
    id: "414",
    name: "Zombie",
    postUrl:
      "https://www.paperforgeminis.com/minis/01086101-240c-4e4b-8741-aa8d3bc2c644",
    folder: "0414",
  },
  {
    id: "415",
    name: "Mimic",
    postUrl:
      "https://www.paperforgeminis.com/minis/6a82c442-924e-466b-8eb7-3f2ddc5ee828",
    folder: "0415",
  },
  {
    id: "416",
    name: "Mimic",
    postUrl:
      "https://www.paperforgeminis.com/minis/6cf648e3-a389-4547-a9bf-2fdb30e421a8",
    folder: "0416",
  },
  {
    id: "417",
    name: "Mindwitness",
    postUrl:
      "https://www.paperforgeminis.com/minis/11176e69-c79b-4095-b54e-085fb882a801",
    folder: "0417",
  },
  {
    id: "418",
    name: "Mimic",
    postUrl:
      "https://www.paperforgeminis.com/minis/20f8b4b2-49cd-48d5-996e-1333d318b814",
    folder: "0418",
  },
  {
    id: "419",
    name: "Noble",
    postUrl:
      "https://www.paperforgeminis.com/minis/07620d54-422e-4273-a3e6-9636b43354c8",
    folder: "0419",
  },
  {
    id: "422",
    name: "Wood Woad",
    postUrl:
      "https://www.paperforgeminis.com/minis/cb7f859e-4fce-4b1b-a656-8243b2dec77c",
    folder: "0422",
  },
  {
    id: "423",
    name: "Nilbog",
    postUrl:
      "https://www.paperforgeminis.com/minis/4a815ac5-280f-4ce1-91cf-a784eb21e2fe",
    folder: "0423",
  },
  {
    id: "426",
    name: "Babau",
    postUrl:
      "https://www.paperforgeminis.com/minis/50c63a64-f90c-4002-b6c6-13ca4e32bede",
    folder: "0426",
  },
  {
    id: "429",
    name: "Zombie Mage",
    postUrl:
      "https://www.paperforgeminis.com/minis/0f1706c9-c2e2-4dd3-a3ff-2b89a161b760",
    folder: "0429",
  },
  {
    id: "430",
    name: "Hobgoblin Iron Shadow",
    postUrl:
      "https://www.paperforgeminis.com/minis/a8c9dc57-374a-44f4-a0b3-65cf5809d781",
    folder: "0430",
  },
  {
    id: "431",
    name: "Goblin Barbarian",
    postUrl:
      "https://www.paperforgeminis.com/minis/ccfb16d3-c249-4665-b1c0-d614f9b825b0",
    folder: "0431",
  },
  {
    id: "434",
    name: "Zombie Crawler",
    postUrl:
      "https://www.paperforgeminis.com/minis/2756d530-2bd0-4711-ad50-32ca1f12d525",
    folder: "0434",
  },
  {
    id: "435",
    name: "Hulking Zombie",
    postUrl:
      "https://www.paperforgeminis.com/minis/d935941c-efe6-470c-a7be-f04a13886689",
    folder: "0435",
  },
  {
    id: "438",
    name: "Flesh Golem",
    postUrl:
      "https://www.paperforgeminis.com/minis/374775ab-b4f0-4ead-92d3-f668a4d57514",
    folder: "0438",
  },
  {
    id: "439",
    name: "Aaracokra Fighter",
    postUrl:
      "https://www.paperforgeminis.com/minis/f8cb0f70-13a0-4df3-9afc-a3bc776acefb",
    folder: "0439",
  },
  {
    id: "440",
    name: "Aaracokra Rogue",
    postUrl:
      "https://www.paperforgeminis.com/minis/aa8b7399-2d64-4123-a375-e5f01cd3babb",
    folder: "0440",
  },
  {
    id: "441",
    name: "Shadow Sorcerer",
    postUrl:
      "https://www.paperforgeminis.com/minis/3a0038b0-b875-43a7-8089-0ded56ac2dcc",
    folder: "0441",
  },
  {
    id: "442",
    name: "Shadow Hound",
    postUrl:
      "https://www.paperforgeminis.com/minis/53972c80-e58a-4edb-904b-abea184b96dd",
    folder: "0442",
  },
  {
    id: "445",
    name: "Octopus",
    postUrl:
      "https://www.paperforgeminis.com/minis/99187c82-db4d-4e3b-a88e-534e14496ba1",
    folder: "0445",
  },
  {
    id: "446",
    name: "Giant Octopus",
    postUrl:
      "https://www.paperforgeminis.com/minis/de2210d4-0ff8-40fe-b83c-cb1a9051c58d",
    folder: "0446",
  },
  {
    id: "447",
    name: "Claspid",
    postUrl:
      "https://www.paperforgeminis.com/minis/9ea8a4ce-6af3-4901-978a-dab1eae2b6e5",
    folder: "0447",
  },
  {
    id: "448",
    name: "Sandstone Golem",
    postUrl:
      "https://www.paperforgeminis.com/minis/41396fcd-6ce0-4624-a660-c359dbc34db8",
    folder: "0448",
  },
  {
    id: "449",
    name: "Ruffian",
    postUrl:
      "https://www.paperforgeminis.com/minis/3716f707-9b06-4743-b25a-6ba8d72538b2",
    folder: "0449",
  },
  {
    id: "450",
    name: "Ruffian",
    postUrl:
      "https://www.paperforgeminis.com/minis/d15c9c1e-8d82-40c8-931b-7ddd0a9e7fc2",
    folder: "0450",
  },
  {
    id: "452",
    name: "Sahuagin",
    postUrl:
      "https://www.paperforgeminis.com/minis/6b97f414-d70c-47ea-bfa5-d6fe1133017a",
    folder: "0452",
  },
  {
    id: "453",
    name: "Ruffian",
    postUrl:
      "https://www.paperforgeminis.com/minis/7a4fc1c7-0073-4ddb-ae1c-ee3f42125952",
    folder: "0453",
  },
  {
    id: "454",
    name: "Ruffian",
    postUrl:
      "https://www.paperforgeminis.com/minis/38985ddc-b448-4b57-ad21-2575155620f7",
    folder: "0454",
  },
  {
    id: "455",
    name: "Reef Shark",
    postUrl:
      "https://www.paperforgeminis.com/minis/38be32e9-5220-4feb-b846-69e4c28c1434",
    folder: "0455",
  },
  {
    id: "456",
    name: "Giant Shark",
    postUrl:
      "https://www.paperforgeminis.com/minis/b66f4626-bbf2-49a5-bc3a-fb1bee7e9bc4",
    folder: "0456",
  },
  {
    id: "457",
    name: "Leonin Barbarian",
    postUrl:
      "https://www.paperforgeminis.com/minis/25f6eb81-793a-4518-ad3e-a36d1a1c8a1c",
    folder: "0457",
  },
  {
    id: "458",
    name: "Leonin Fighter",
    postUrl:
      "https://www.paperforgeminis.com/minis/59b4da7d-656d-490a-a3e6-6d79e89db5ad",
    folder: "0458",
  },
  {
    id: "459",
    name: "Half Elf Ranger",
    postUrl:
      "https://www.paperforgeminis.com/minis/30466327-a8f7-4cb7-bb62-cfee22daca16",
    folder: "0459",
  },
  {
    id: "461",
    name: "Monk",
    postUrl:
      "https://www.paperforgeminis.com/minis/b6f47fe5-b77d-4c4d-8658-e4e43629fc54",
    folder: "0461",
  },
  {
    id: "463",
    name: "Kenku Thief",
    postUrl:
      "https://www.paperforgeminis.com/minis/993843af-cca2-4f3b-ab12-9dac17622c8f",
    folder: "0463",
  },
  {
    id: "466",
    name: "Druid",
    postUrl:
      "https://www.paperforgeminis.com/minis/a1d92778-54a5-4116-be3d-cae60126ade7",
    folder: "0466",
  },
  {
    id: "468",
    name: "Auto-gnome",
    postUrl:
      "https://www.paperforgeminis.com/minis/f5b1e452-a77b-4986-8855-a06eda004dc9",
    folder: "0468",
  },
  {
    id: "473",
    name: "Giff Warlord",
    postUrl:
      "https://www.paperforgeminis.com/minis/026ac619-1363-49dc-b2f7-86da94473f4c",
    folder: "0473",
  },
  {
    id: "474",
    name: "Brawler",
    postUrl:
      "https://www.paperforgeminis.com/minis/af25f876-109a-4f82-ba8c-04ddc2539de2",
    folder: "0474",
  },
  {
    id: "478",
    name: "Vampire",
    postUrl:
      "https://www.paperforgeminis.com/minis/7fe8eda5-7d24-48b7-8c7c-fa1c22f85b83",
    folder: "0478",
  },
  {
    id: "480",
    name: "Star Lancer",
    postUrl:
      "https://www.paperforgeminis.com/minis/76e8da9b-777b-4161-b198-54a4d75419b0",
    folder: "0480",
  },
  {
    id: "481",
    name: "Vampire",
    postUrl:
      "https://www.paperforgeminis.com/minis/b4e52f53-bdf4-4d4d-8b9a-b775c47f8c26",
    folder: "0481",
  },
  {
    id: "483",
    name: "Vampire",
    postUrl:
      "https://www.paperforgeminis.com/minis/9b351522-9b92-4276-b8e5-b9ebe55f421a",
    folder: "0483",
  },
  {
    id: "485",
    name: "Scarecrow",
    postUrl:
      "https://www.paperforgeminis.com/minis/6e7302c5-b651-4b98-8ac5-8ab0c855958c",
    folder: "0485",
  },
  {
    id: "488",
    name: "Nobleman",
    postUrl:
      "https://www.paperforgeminis.com/minis/043ff4f7-cb4a-48e7-b468-bb537119e916",
    folder: "0488",
  },
  {
    id: "489",
    name: "Autognome",
    postUrl:
      "https://www.paperforgeminis.com/minis/99e56dce-2280-44aa-a62b-e7a98172fb95",
    folder: "0489",
  },
  {
    id: "490",
    name: "Werewolf",
    postUrl:
      "https://www.paperforgeminis.com/minis/db9cba4d-3b93-444c-83f5-6699ee3f94ea",
    folder: "0490",
  },
  {
    id: "492",
    name: "Ooze",
    postUrl:
      "https://www.paperforgeminis.com/minis/77a6fca5-9cf4-474a-8f8e-466aed99a7ff",
    folder: "0492",
  },
  {
    id: "493",
    name: "Slithering Tracker",
    postUrl:
      "https://www.paperforgeminis.com/minis/b03be352-2758-45f0-852a-0d5bffd6bab6",
    folder: "0493",
  },
  {
    id: "494",
    name: "Bugbear",
    postUrl:
      "https://www.paperforgeminis.com/minis/ca26a821-f858-4ac7-bb57-9cd9a719cf07",
    folder: "0494",
  },
  {
    id: "495",
    name: "Ettin",
    postUrl:
      "https://www.paperforgeminis.com/minis/3f5349f5-adbc-4fa3-81b4-7e7c72acf315",
    folder: "0495",
  },
  {
    id: "497",
    name: "Fomorian",
    postUrl:
      "https://www.paperforgeminis.com/minis/e83f3b0c-76a7-432e-9032-f47e948cb977",
    folder: "0497",
  },
  {
    id: "502",
    name: "Road Bandit",
    postUrl:
      "https://www.paperforgeminis.com/minis/7fc5982b-07cf-49be-bb47-f7bbedbdae78",
    folder: "0502",
  },
  {
    id: "504",
    name: "Gorgon",
    postUrl:
      "https://www.paperforgeminis.com/minis/37290966-56d2-4707-b013-e0073a5ba021",
    folder: "0504",
  },
  {
    id: "505",
    name: "Bandit Spellcaster",
    postUrl:
      "https://www.paperforgeminis.com/minis/9db83556-f36a-4639-b497-37597c95bb2d",
    folder: "0505",
  },
  {
    id: "506",
    name: "Chain Devil",
    postUrl:
      "https://www.paperforgeminis.com/minis/c9367271-1198-4ce3-99f4-a14ea53fcf86",
    folder: "0506",
  },
  {
    id: "507",
    name: "Animated Chains",
    postUrl:
      "https://www.paperforgeminis.com/minis/db43dace-30d7-472e-83ff-91d42e28279b",
    folder: "0507",
  },
  {
    id: "508",
    name: "Marilith",
    postUrl:
      "https://www.paperforgeminis.com/minis/b3563f91-c9bf-42e8-8ff2-34f19347c89b",
    folder: "0508",
  },
  {
    id: "511",
    name: "Pit Fiend",
    postUrl:
      "https://www.paperforgeminis.com/minis/4f722624-50ce-4228-821c-42e76b43c849",
    folder: "0511",
  },
  {
    id: "512",
    name: "Bat",
    postUrl:
      "https://www.paperforgeminis.com/minis/313e69a5-a8d3-4a1a-b7ee-2808a5a88efe",
    folder: "0512",
  },
  {
    id: "514",
    name: "Vampire Lord",
    postUrl:
      "https://www.paperforgeminis.com/minis/f9399a64-6950-47e5-a21a-6443c8c0fbf6",
    folder: "0514",
  },
  {
    id: "520",
    name: "Treant",
    postUrl:
      "https://www.paperforgeminis.com/minis/a08f5b2a-6d3a-427e-874a-4befe49c8173",
    folder: "0520",
  },
  {
    id: "521",
    name: "Awakened Shrub",
    postUrl:
      "https://www.paperforgeminis.com/minis/4c723778-73fe-45e4-bb08-644e1bed3168",
    folder: "0521",
  },
  {
    id: "522",
    name: "Awakened Shrub",
    postUrl:
      "https://www.paperforgeminis.com/minis/172fd273-ab1f-46fa-b295-cc1df75fffbf",
    folder: "0522",
  },
  {
    id: "523",
    name: "Goblin Pathfinder",
    postUrl:
      "https://www.paperforgeminis.com/minis/d02abd79-b0f3-4a08-b64e-3fd8b057a34f",
    folder: "0523",
  },
  {
    id: "524",
    name: "Goblin Pathfinder",
    postUrl:
      "https://www.paperforgeminis.com/minis/f22aa3bb-3701-499f-9c7e-fcb9dc799dc0",
    folder: "0524",
  },
  {
    id: "525",
    name: "Goblin Pathfinder",
    postUrl:
      "https://www.paperforgeminis.com/minis/a89a7c74-fe6d-44cb-85ab-86fbb431db5e",
    folder: "0525",
  },
  {
    id: "526",
    name: "Oni",
    postUrl:
      "https://www.paperforgeminis.com/minis/873c7597-b6a8-407a-ad8b-999c19f92fca",
    folder: "0526",
  },
  {
    id: "527",
    name: "Goblin Pathfinder",
    postUrl:
      "https://www.paperforgeminis.com/minis/43bea0ca-1d1b-4481-861f-ef618ded67f8",
    folder: "0527",
  },
  {
    id: "528",
    name: "Goblin Pathfinder",
    postUrl:
      "https://www.paperforgeminis.com/minis/bbd31e7b-10f4-41c8-a237-bbc23c317e3b",
    folder: "0528",
  },
  {
    id: "530",
    name: "The Butcher",
    postUrl:
      "https://www.paperforgeminis.com/minis/932b16a6-c8ec-4349-b440-3fceafe739dd",
    folder: "0530",
  },
  {
    id: "531",
    name: "Shadow Demon",
    postUrl:
      "https://www.paperforgeminis.com/minis/0b9a019f-b12e-498e-a116-a438c05e9d0e",
    folder: "0531",
  },
  {
    id: "532",
    name: "Sailor",
    postUrl:
      "https://www.paperforgeminis.com/minis/af197382-23f8-41a8-a5be-1cf3f28a1b84",
    folder: "0532",
  },
  {
    id: "534",
    name: "Lich",
    postUrl:
      "https://www.paperforgeminis.com/minis/5d8889d7-2033-474d-b425-626c318b6ce6",
    folder: "0534",
  },
  {
    id: "536",
    name: "Pikeman",
    postUrl:
      "https://www.paperforgeminis.com/minis/ddc28800-41c4-4f49-97bb-65ad86020152",
    folder: "0536",
  },
  {
    id: "542",
    name: "Draconian Dreadnought",
    postUrl:
      "https://www.paperforgeminis.com/minis/593a686f-8b90-40ab-bf48-b2192a8c4429",
    folder: "0542",
  },
  {
    id: "545",
    name: "Draconian Footsoldier",
    postUrl:
      "https://www.paperforgeminis.com/minis/f7771a29-6100-4d17-9df9-6078cf198c38",
    folder: "0545",
  },
  {
    id: "547",
    name: "Horse",
    postUrl:
      "https://www.paperforgeminis.com/minis/e9bcdb16-1e24-438e-8297-c3c92c1b76be",
    folder: "0547",
  },
  {
    id: "549",
    name: "Mule",
    postUrl:
      "https://www.paperforgeminis.com/minis/94ec628f-918b-4c57-9935-391aed863601",
    folder: "0549",
  },
  {
    id: "552",
    name: "TwigBlight",
    postUrl:
      "https://www.paperforgeminis.com/minis/7acf1947-24d4-4884-8ce9-0c82357d9cba",
    folder: "0552",
  },
  {
    id: "553",
    name: "Twig Blight",
    postUrl:
      "https://www.paperforgeminis.com/minis/51dca3fc-130a-4a19-bc0b-06726122cb04",
    folder: "0553",
  },
  {
    id: "554",
    name: "Kyra",
    postUrl:
      "https://www.paperforgeminis.com/minis/db8eaf34-f6f9-4576-8085-7441e20aa11f",
    folder: "0554",
  },
  {
    id: "556",
    name: "Fighter",
    postUrl:
      "https://www.paperforgeminis.com/minis/9d7296b1-a9b7-43ae-a7c2-11bb4583adbb",
    folder: "0556",
  },
  {
    id: "559",
    name: "Sahuagin Baron",
    postUrl:
      "https://www.paperforgeminis.com/minis/b70706f0-2322-43ad-9401-5517a05f56ae",
    folder: "0559",
  },
  {
    id: "560",
    name: "Sahuagin Priestess",
    postUrl:
      "https://www.paperforgeminis.com/minis/86838eba-3fd9-4654-88b3-a2c91c8e92d3",
    folder: "0560",
  },
  {
    id: "562",
    name: "Fox",
    postUrl:
      "https://www.paperforgeminis.com/minis/62566f78-a454-4f2c-83d1-ec194f815bf4",
    folder: "0562",
  },
  {
    id: "563",
    name: "Stirge",
    postUrl:
      "https://www.paperforgeminis.com/minis/c2ee86aa-a805-4769-86d0-be6ea4602225",
    folder: "0563",
  },
  {
    id: "566",
    name: "Shambling Mound",
    postUrl:
      "https://www.paperforgeminis.com/minis/988799a8-d08e-4eae-964d-91b33b5a5265",
    folder: "0566",
  },
  {
    id: "567",
    name: "Force Ballista",
    postUrl:
      "https://www.paperforgeminis.com/minis/cbcf3512-bb68-4934-ba74-5313e56aac6b",
    folder: "0567",
  },
  {
    id: "568",
    name: "Flamethrower",
    postUrl:
      "https://www.paperforgeminis.com/minis/44cdf475-5e6d-46cb-b314-7e22b606cd6b",
    folder: "0568",
  },
  {
    id: "569",
    name: "Protector",
    postUrl:
      "https://www.paperforgeminis.com/minis/be8ccd11-ee3e-4005-b17c-c0f80fbfede4",
    folder: "0569",
  },
  {
    id: "571",
    name: "Crab",
    postUrl:
      "https://www.paperforgeminis.com/minis/158f95b8-60f8-460b-bb97-1f8e7dd57653",
    folder: "0571",
  },
  {
    id: "572",
    name: "Magmin",
    postUrl:
      "https://www.paperforgeminis.com/minis/e13c3bdf-bf29-4ac2-8247-93be937030bc",
    folder: "0572",
  },
  {
    id: "575",
    name: "Earth Elemental",
    postUrl:
      "https://www.paperforgeminis.com/minis/b09a9b29-ea61-4132-a2e9-d30957f097c0",
    folder: "0575",
  },
  {
    id: "576",
    name: "Merisiel",
    postUrl:
      "https://www.paperforgeminis.com/minis/550ee4ec-9c79-4e31-8ab2-d46528c8c407",
    folder: "0576",
  },
  {
    id: "577",
    name: "Air Elemental",
    postUrl:
      "https://www.paperforgeminis.com/minis/2fdb2897-bd86-4951-94ea-790991bc14c9",
    folder: "0577",
  },
  {
    id: "578",
    name: " Water Elemental",
    postUrl:
      "https://www.paperforgeminis.com/minis/a6a9bb2a-24e1-4569-a13e-d869418f972b",
    folder: "0578",
  },
  {
    id: "579",
    name: "Magma Mephit",
    postUrl:
      "https://www.paperforgeminis.com/minis/a8369ef3-4b05-46a1-97f7-8ffdd072f8a0",
    folder: "0579",
  },
  {
    id: "580",
    name: "Ice Mephit",
    postUrl:
      "https://www.paperforgeminis.com/minis/13061994-611b-4246-b540-6580299271bd",
    folder: "0580",
  },
  {
    id: "581",
    name: "Mud Mephit",
    postUrl:
      "https://www.paperforgeminis.com/minis/0fa023f6-e10a-443d-83a8-72af289e155a",
    folder: "0581",
  },
  {
    id: "582",
    name: "Smoke Mephit",
    postUrl:
      "https://www.paperforgeminis.com/minis/fee9b662-3c91-4e2f-821b-953da9825b55",
    folder: "0582",
  },
  {
    id: "583",
    name: "Fire Elemental",
    postUrl:
      "https://www.paperforgeminis.com/minis/dc59fa97-141d-494a-8bb7-330997b490bc",
    folder: "0583",
  },
  {
    id: "585",
    name: "Valeros",
    postUrl:
      "https://www.paperforgeminis.com/minis/39b24204-0c18-4471-a539-df2be1cbb076",
    folder: "0585",
  },
  {
    id: "586",
    name: "Valeros",
    postUrl:
      "https://www.paperforgeminis.com/minis/926fe7da-e9ef-475b-871b-a005ad587828",
    folder: "0586",
  },
  {
    id: "587",
    name: "Animated Armor",
    postUrl:
      "https://www.paperforgeminis.com/minis/c76dcdcd-210e-41a5-9fc8-806c67cde195",
    folder: "0587",
  },
  {
    id: "589",
    name: "Animated Armor",
    postUrl:
      "https://www.paperforgeminis.com/minis/755f359b-ad83-4527-af39-3f1022b3d6ce",
    folder: "0589",
  },
  {
    id: "591",
    name: "Sharklin",
    postUrl:
      "https://www.paperforgeminis.com/minis/4b0ed966-e279-4036-8c18-7cd92e8aa443",
    folder: "0591",
  },
  {
    id: "592",
    name: "Sharklin Netter",
    postUrl:
      "https://www.paperforgeminis.com/minis/53b4bda2-d748-4a2b-b512-c88d524a3cdb",
    folder: "0592",
  },
  {
    id: "593",
    name: "Sharklin Harpooner",
    postUrl:
      "https://www.paperforgeminis.com/minis/0297d01d-b725-4732-9972-d67fee7bb277",
    folder: "0593",
  },
  {
    id: "595",
    name: "Beholder",
    postUrl:
      "https://www.paperforgeminis.com/minis/1e2db3a1-f849-447d-9e92-4d672f69fa0c",
    folder: "0595",
  },
  {
    id: "596",
    name: "Knight",
    postUrl:
      "https://www.paperforgeminis.com/minis/6403c397-377d-4dc4-9f4e-9909c3d94659",
    folder: "0596",
  },
  {
    id: "598",
    name: "Gibbering Mouther",
    postUrl:
      "https://www.paperforgeminis.com/minis/33cd3cf6-2f8a-411d-828b-2d538158bc33",
    folder: "0598",
  },
  {
    id: "599",
    name: "Ranger",
    postUrl:
      "https://www.paperforgeminis.com/minis/4ebfd22e-c37d-4fbc-a36d-4bb5866e9e62",
    folder: "0599",
  },
  {
    id: "601",
    name: "Hobgoblin Soldier",
    postUrl:
      "https://www.paperforgeminis.com/minis/bfe7d100-59d5-4ac7-be60-6bde98cca609",
    folder: "0601",
  },
  {
    id: "602",
    name: "Hobgoblin Soldier",
    postUrl:
      "https://www.paperforgeminis.com/minis/c7df7a34-502a-46e1-b442-fa1da34609c4",
    folder: "0602",
  },
  {
    id: "603",
    name: "Hobgoblin Soldier",
    postUrl:
      "https://www.paperforgeminis.com/minis/30a8c04e-d6a7-4834-b751-259d1dde6750",
    folder: "0603",
  },
  {
    id: "604",
    name: "The Overseer",
    postUrl:
      "https://www.paperforgeminis.com/minis/485ffcaf-e5c3-4034-b3f8-f272e38aee04",
    folder: "0604",
  },
  {
    id: "605",
    name: "Undead Worker",
    postUrl:
      "https://www.paperforgeminis.com/minis/1a8e9eb2-4be6-4b1e-ad86-208812592a48",
    folder: "0605",
  },
  {
    id: "606",
    name: "Undead Worker",
    postUrl:
      "https://www.paperforgeminis.com/minis/b664e9a0-e6dc-4945-b343-bd0858ff21aa",
    folder: "0606",
  },
  {
    id: "607",
    name: "Giant Rat",
    postUrl:
      "https://www.paperforgeminis.com/minis/349fda72-352f-4090-9d90-fdc6f277b41e",
    folder: "0607",
  },
  {
    id: "608",
    name: "Cyclops",
    postUrl:
      "https://www.paperforgeminis.com/minis/2d3ca690-c94b-48f2-ba31-4d7c95bc7077",
    folder: "0608",
  },
  {
    id: "614",
    name: "Seelah",
    postUrl:
      "https://www.paperforgeminis.com/minis/0a80de97-4522-4dd2-9e31-b93f2958c7be",
    folder: "0614",
  },
  {
    id: "615",
    name: "Commoner",
    postUrl:
      "https://www.paperforgeminis.com/minis/0325e920-4751-4b9a-b351-d69b774999c4",
    folder: "0615",
  },
  {
    id: "616",
    name: "Commoner",
    postUrl:
      "https://www.paperforgeminis.com/minis/88c8582c-cacc-4efc-96b8-60dcca9118f7",
    folder: "0616",
  },
  {
    id: "618",
    name: "Commoner",
    postUrl:
      "https://www.paperforgeminis.com/minis/98690608-95e4-4f8b-8e91-7ec62ea6e1cc",
    folder: "0618",
  },
  {
    id: "619",
    name: "Commoner ",
    postUrl:
      "https://www.paperforgeminis.com/minis/34a6a275-9529-4c6c-bb42-3a59f15cf4d6",
    folder: "0619",
  },
  {
    id: "622",
    name: "Priestess",
    postUrl:
      "https://www.paperforgeminis.com/minis/d41dbb83-46d6-44bc-ac1c-dfb49ee154f4",
    folder: "0622",
  },
  {
    id: "623",
    name: "Storm Giant",
    postUrl:
      "https://www.paperforgeminis.com/minis/628af413-95b9-48ed-974d-5fba54018016",
    folder: "0623",
  },
  {
    id: "630",
    name: "Vampire Spawn",
    postUrl:
      "https://www.paperforgeminis.com/minis/2365a7e5-09d2-4fd8-b4c1-9481afed9cb2",
    folder: "0630",
  },
  {
    id: "631",
    name: "Infected Townswoman",
    postUrl:
      "https://www.paperforgeminis.com/minis/0de7f86f-4876-4957-a2af-39186539aa43",
    folder: "0631",
  },
  {
    id: "632",
    name: "Snake Priestess",
    postUrl:
      "https://www.paperforgeminis.com/minis/e64e273d-349b-4d7e-ad1e-97d08c03be48",
    folder: "0632",
  },
  {
    id: "634",
    name: "Vampire Spawn",
    postUrl:
      "https://www.paperforgeminis.com/minis/9f6f6ea1-5ae8-4ffb-b1b8-b8ee550854e2",
    folder: "0634",
  },
  {
    id: "635",
    name: "Infected Townsman",
    postUrl:
      "https://www.paperforgeminis.com/minis/b27de0b9-a055-42a1-acc2-c1788a0594e3",
    folder: "0635",
  },
  {
    id: "636",
    name: "Commoner",
    postUrl:
      "https://www.paperforgeminis.com/minis/4418e49b-657b-4f97-a620-06cca506d86f",
    folder: "0636",
  },
  {
    id: "637",
    name: "Commoner",
    postUrl:
      "https://www.paperforgeminis.com/minis/52ea4c53-b64d-4bf5-b19b-2466188332d3",
    folder: "0637",
  },
  {
    id: "638",
    name: "Commoner",
    postUrl:
      "https://www.paperforgeminis.com/minis/c8149a75-3d61-4e10-aafd-4d244e5b2e5c",
    folder: "0638",
  },
  {
    id: "639",
    name: "Cleric",
    postUrl:
      "https://www.paperforgeminis.com/minis/c1758736-1a1b-44b1-8647-79fcd8d6367d",
    folder: "0639",
  },
  {
    id: "640",
    name: "Acid Zombie",
    postUrl:
      "https://www.paperforgeminis.com/minis/96204e12-8b22-466f-8ee6-94fc77121cbc",
    folder: "0640",
  },
  {
    id: "641",
    name: "Druid",
    postUrl:
      "https://www.paperforgeminis.com/minis/33047044-ab6d-4dde-975c-4764d6ccfac0",
    folder: "0641",
  },
  {
    id: "642",
    name: "Dire Bat",
    postUrl:
      "https://www.paperforgeminis.com/minis/ea949e8d-ffe7-4771-87c5-0f363b332489",
    folder: "0642",
  },
  {
    id: "643",
    name: "War Bat",
    postUrl:
      "https://www.paperforgeminis.com/minis/d1d676bd-08de-4223-8a22-2290c8882894",
    folder: "0643",
  },
  {
    id: "644",
    name: "Goblin Bat Rider",
    postUrl:
      "https://www.paperforgeminis.com/minis/a25f895d-0d11-4652-a040-4ad76ae7100c",
    folder: "0644",
  },
  {
    id: "648",
    name: "PaperBoy",
    postUrl:
      "https://www.paperforgeminis.com/minis/a9c94e0b-409f-4a95-817b-0737388f7dca",
    folder: "0648",
  },
  {
    id: "650",
    name: "Guard",
    postUrl:
      "https://www.paperforgeminis.com/minis/a6403721-9be2-4112-a9d5-c333fbe60e0f",
    folder: "0650",
  },
  {
    id: "651",
    name: "Guard",
    postUrl:
      "https://www.paperforgeminis.com/minis/ed826078-f654-4051-ab43-9cfeecbfa69b",
    folder: "0651",
  },
  {
    id: "652",
    name: "Guard",
    postUrl:
      "https://www.paperforgeminis.com/minis/79bf7def-927f-451a-8ff7-619d9d41baf8",
    folder: "0652",
  },
  {
    id: "653",
    name: "Guard",
    postUrl:
      "https://www.paperforgeminis.com/minis/43ff2e38-787f-483d-9b1a-64b86e3d6ccb",
    folder: "0653",
  },
  {
    id: "654",
    name: "Guard",
    postUrl:
      "https://www.paperforgeminis.com/minis/8d069fa1-d871-4828-818c-392ed790804c",
    folder: "0654",
  },
  {
    id: "655",
    name: "Giant Raven",
    postUrl:
      "https://www.paperforgeminis.com/minis/7d8c02d6-1bc6-4fad-a332-4f23260bbb9c",
    folder: "0655",
  },
  {
    id: "656",
    name: "Child",
    postUrl:
      "https://www.paperforgeminis.com/minis/b6b8bcb7-6ab0-443c-aaba-31200e304b83",
    folder: "0656",
  },
  {
    id: "657",
    name: "Child",
    postUrl:
      "https://www.paperforgeminis.com/minis/762a2aae-ba5e-4686-9932-dcddac65ec37",
    folder: "0657",
  },
  {
    id: "658",
    name: "Child",
    postUrl:
      "https://www.paperforgeminis.com/minis/999e4189-27f4-4fca-bd8f-ae8338791ad6",
    folder: "0658",
  },
  {
    id: "659",
    name: "Child",
    postUrl:
      "https://www.paperforgeminis.com/minis/fcdcde6a-92c4-4ae7-8da0-354dc3493af7",
    folder: "0659",
  },
  {
    id: "660",
    name: "Adult Kruthik",
    postUrl:
      "https://www.paperforgeminis.com/minis/80481305-ac37-4cb5-8065-12f03081c1ec",
    folder: "0660",
  },
  {
    id: "661",
    name: "Young Kruthik",
    postUrl:
      "https://www.paperforgeminis.com/minis/b0a575b8-fa55-44f2-857b-04afe886817a",
    folder: "0661",
  },
  {
    id: "665",
    name: "Umber Hulk",
    postUrl:
      "https://www.paperforgeminis.com/minis/aaeebf11-f957-4139-8ecc-4f3007df57c4",
    folder: "0665",
  },
  {
    id: "666",
    name: "Asmodeus",
    postUrl:
      "https://www.paperforgeminis.com/minis/c8dfb0fe-8f72-46ff-a7eb-dd8cd02962e5",
    folder: "0666",
  },
  {
    id: "667",
    name: "Ezren",
    postUrl:
      "https://www.paperforgeminis.com/minis/9a44b7f3-44bd-43d3-8055-164a9d4bf689",
    folder: "0667",
  },
  {
    id: "670",
    name: "Gatorling",
    postUrl:
      "https://www.paperforgeminis.com/minis/f5ed71ca-33fc-4a37-8c28-921393d3a74c",
    folder: "0670",
  },
  {
    id: "671",
    name: "Gatorling",
    postUrl:
      "https://www.paperforgeminis.com/minis/9228ec17-39c2-48ca-9dc0-1527651b4554",
    folder: "0671",
  },
  {
    id: "672",
    name: "Gartorling",
    postUrl:
      "https://www.paperforgeminis.com/minis/220ee3a4-1a24-4094-8fea-2a889500a0c9",
    folder: "0672",
  },
  {
    id: "673",
    name: "Gatorling",
    postUrl:
      "https://www.paperforgeminis.com/minis/db6d4478-9688-4f61-b610-824f5cdf4c01",
    folder: "0673",
  },
  {
    id: "674",
    name: "Le Douanier",
    postUrl:
      "https://www.paperforgeminis.com/minis/20887283-f6d0-47a5-8df2-1218c131d649",
    folder: "0674",
  },
  {
    id: "675",
    name: "Undead Warrior",
    postUrl:
      "https://www.paperforgeminis.com/minis/2f06b95f-fbab-4ddc-890e-5b0ac71f9164",
    folder: "0675",
  },
  {
    id: "677",
    name: "Undead Archer",
    postUrl:
      "https://www.paperforgeminis.com/minis/6d56139c-daa8-4ab6-9940-798cd70970cb",
    folder: "0677",
  },
  {
    id: "679",
    name: "SharklinChief",
    postUrl:
      "https://www.paperforgeminis.com/minis/ce8e2e8b-93d4-477e-99d3-c0c3aafd81bb",
    folder: "0679",
  },
  {
    id: "680",
    name: "Barbarian",
    postUrl:
      "https://www.paperforgeminis.com/minis/a1dc2c20-4a2d-4f47-8959-df355a139dfe",
    folder: "0680",
  },
  {
    id: "683",
    name: "Novice Fighter",
    postUrl:
      "https://www.paperforgeminis.com/minis/e3164970-538e-4c81-9fea-136c7e1a4e99",
    folder: "0683",
  },
  {
    id: "684",
    name: "Novice Wizard",
    postUrl:
      "https://www.paperforgeminis.com/minis/5994b762-446a-4e9e-a4b5-c7c6dc4ce778",
    folder: "0684",
  },
  {
    id: "685",
    name: "Gelatinous Cube",
    postUrl:
      "https://www.paperforgeminis.com/minis/adeb6009-e035-46b0-9771-a6b2873b68d4",
    folder: "0685",
  },
  {
    id: "688",
    name: "Novice Cleric",
    postUrl:
      "https://www.paperforgeminis.com/minis/63c50858-0f5b-4686-ab03-08bccaa73c59",
    folder: "0688",
  },
  {
    id: "689",
    name: "Novice Rogue",
    postUrl:
      "https://www.paperforgeminis.com/minis/e54bd502-8561-44e5-ba3e-a8597b0bd409",
    folder: "0689",
  },
  {
    id: "690",
    name: "Dog",
    postUrl:
      "https://www.paperforgeminis.com/minis/dc8c2c9e-b1b2-471d-adb8-1e5e91d87942",
    folder: "0690",
  },
  {
    id: "691",
    name: "Dog",
    postUrl:
      "https://www.paperforgeminis.com/minis/793b8c99-779a-49ad-9759-6f0c7c1bb303",
    folder: "0691",
  },
  {
    id: "694",
    name: "Blink Dog",
    postUrl:
      "https://www.paperforgeminis.com/minis/83a5da13-5c08-4acb-9c75-9e70f988d193",
    folder: "0694",
  },
  {
    id: "696",
    name: "Kenku",
    postUrl:
      "https://www.paperforgeminis.com/minis/ef0363a1-5d94-4f12-8498-afb0b2d35aed",
    folder: "0696",
  },
  {
    id: "697",
    name: "Kenku",
    postUrl:
      "https://www.paperforgeminis.com/minis/dd1ec1f3-622e-4ea1-a0b0-045950e588f9",
    folder: "0697",
  },
  {
    id: "700",
    name: "Novice Monk",
    postUrl:
      "https://www.paperforgeminis.com/minis/26daa4f0-ed6b-49bc-bba0-65e5caf037cd",
    folder: "0700",
  },
  {
    id: "701",
    name: "Mermaid",
    postUrl:
      "https://www.paperforgeminis.com/minis/366f62f3-f793-48db-85d5-ebb6f879ef5d",
    folder: "0701",
  },
  {
    id: "702",
    name: "Siren",
    postUrl:
      "https://www.paperforgeminis.com/minis/8aa6ffed-5438-446d-8eaa-0d07fd09bfa4",
    folder: "0702",
  },
  {
    id: "704",
    name: "Axe Beak",
    postUrl:
      "https://www.paperforgeminis.com/minis/d8d6f70e-47c0-43c3-a03d-62ce54523cea",
    folder: "0704",
  },
  {
    id: "708",
    name: "Pit fighter",
    postUrl:
      "https://www.paperforgeminis.com/minis/cef7997b-5d02-433a-b6c8-223af35a705c",
    folder: "0708",
  },
  {
    id: "709",
    name: "Pit fighter",
    postUrl:
      "https://www.paperforgeminis.com/minis/b3356f3e-ff89-4e53-ae96-24c92c3951be",
    folder: "0709",
  },
  {
    id: "710",
    name: "Pit fighter",
    postUrl:
      "https://www.paperforgeminis.com/minis/a7a6129a-5650-4a9b-9a97-9621c8d5ae23",
    folder: "0710",
  },
  {
    id: "711",
    name: "Pit fighter",
    postUrl:
      "https://www.paperforgeminis.com/minis/8605a6c7-8375-4158-8d74-3a0c0d41b9ab",
    folder: "0711",
  },
  {
    id: "715",
    name: "General Goods Merchant",
    postUrl:
      "https://www.paperforgeminis.com/minis/90dc549d-d329-4af9-ae0c-9dbbfa0b2b79",
    folder: "0715",
  },
  {
    id: "716",
    name: "General Goods Merchant",
    postUrl:
      "https://www.paperforgeminis.com/minis/1ea0a1aa-eb97-4335-942b-1b9d69b07534",
    folder: "0716",
  },
  {
    id: "720",
    name: "Dragon Wyrmling",
    postUrl:
      "https://www.paperforgeminis.com/minis/afdd929c-6370-4249-9432-09fb7cb2cd14",
    folder: "0720",
  },
  {
    id: "721",
    name: "Dragon Eggs",
    postUrl:
      "https://www.paperforgeminis.com/minis/bfd4a90e-6843-4e20-a52a-33f2b34268b2",
    folder: "0721",
  },
  {
    id: "722",
    name: "Psi Brawler",
    postUrl:
      "https://www.paperforgeminis.com/minis/85ab8e58-577f-4d74-b635-c93f19a38975",
    folder: "0722",
  },
  {
    id: "723",
    name: "Psi Commander",
    postUrl:
      "https://www.paperforgeminis.com/minis/712755df-c20c-42e4-aef0-bababecbc9b5",
    folder: "0723",
  },
  {
    id: "724",
    name: "Psi Swordman",
    postUrl:
      "https://www.paperforgeminis.com/minis/3385e1e6-4b89-4a0f-ba56-fdfce875565b",
    folder: "0724",
  },
  {
    id: "725",
    name: "Psi Chosen One",
    postUrl:
      "https://www.paperforgeminis.com/minis/43ca9f9a-f259-44ed-b117-da463043f638",
    folder: "0725",
  },
  {
    id: "726",
    name: "Psi Brawler",
    postUrl:
      "https://www.paperforgeminis.com/minis/473c2a16-d993-4c7a-b267-550d8c012911",
    folder: "0726",
  },
  {
    id: "727",
    name: "Grick",
    postUrl:
      "https://www.paperforgeminis.com/minis/6ab4a4a7-da46-4f91-b77a-316c4ea4dcdc",
    folder: "0727",
  },
  {
    id: "728",
    name: "Violet Fungus Necrohulk",
    postUrl:
      "https://www.paperforgeminis.com/minis/358a4199-4b1b-4514-85c7-a5452a0bf264",
    folder: "0728",
  },
  {
    id: "729",
    name: "Githyanki Warrior",
    postUrl:
      "https://www.paperforgeminis.com/minis/5c63edb9-2548-483a-9257-f241ca69f426",
    folder: "0729",
  },
  {
    id: "730",
    name: "Githyanki Warrior",
    postUrl:
      "https://www.paperforgeminis.com/minis/d893078c-49ef-45ea-9025-e2a77e2c5b9a",
    folder: "0730",
  },
  {
    id: "731",
    name: "Githyanki Knight",
    postUrl:
      "https://www.paperforgeminis.com/minis/3bf56f7e-5e3e-4475-bf19-815d205e5466",
    folder: "0731",
  },
  {
    id: "732",
    name: "Githyanki  Dracomancer",
    postUrl:
      "https://www.paperforgeminis.com/minis/9ff36c3b-486f-4de7-926d-007b55e74265",
    folder: "0732",
  },
  {
    id: "733",
    name: "Cloaker",
    postUrl:
      "https://www.paperforgeminis.com/minis/afb47c70-9726-4c6c-abfb-a44e7996c1a9",
    folder: "0733",
  },
  {
    id: "734",
    name: "Cloaker",
    postUrl:
      "https://www.paperforgeminis.com/minis/45745a42-5740-4e85-96f7-b2b77b7df528",
    folder: "0734",
  },
  {
    id: "735",
    name: "Ochre Jelly",
    postUrl:
      "https://www.paperforgeminis.com/minis/fc224602-fcdd-41c1-a317-b39615d156b7",
    folder: "0735",
  },
  {
    id: "737",
    name: "Githzerai Monk",
    postUrl:
      "https://www.paperforgeminis.com/minis/4c6bcb62-f7b3-42af-a7f8-f6d3651fe863",
    folder: "0737",
  },
  {
    id: "738",
    name: "Githzerai Monk",
    postUrl:
      "https://www.paperforgeminis.com/minis/66366db3-2b00-4286-ab85-33978a7eff9b",
    folder: "0738",
  },
  {
    id: "739",
    name: "Githzerai Zerth",
    postUrl:
      "https://www.paperforgeminis.com/minis/b2d02549-9835-4fd3-8edc-888da1331f4f",
    folder: "0739",
  },
  {
    id: "740",
    name: "Githzerai Psion",
    postUrl:
      "https://www.paperforgeminis.com/minis/24c54f16-926c-4ef2-bbe3-60d337d901d6",
    folder: "0740",
  },
  {
    id: "741",
    name: "Dead Townspeople",
    postUrl:
      "https://www.paperforgeminis.com/minis/7b005740-4262-4dbd-9655-d676e942a113",
    folder: "0741",
  },
  {
    id: "742",
    name: "Dead Townspeople",
    postUrl:
      "https://www.paperforgeminis.com/minis/df30c108-4625-49f9-b5c4-8909e13a6a30",
    folder: "0742",
  },
  {
    id: "743",
    name: "Dead Townspeople",
    postUrl:
      "https://www.paperforgeminis.com/minis/cc41096c-b466-452e-94d5-341de5f0237e",
    folder: "0743",
  },
  {
    id: "744",
    name: "Dead Townspeople",
    postUrl:
      "https://www.paperforgeminis.com/minis/ac39dda7-b1f8-4602-a54b-fd14110307f6",
    folder: "0744",
  },
  {
    id: "745",
    name: "Dead Townspeople",
    postUrl:
      "https://www.paperforgeminis.com/minis/a4ed12bc-ff38-4574-adbf-9ff2061b989e",
    folder: "0745",
  },
  {
    id: "746",
    name: "Dead Guard",
    postUrl:
      "https://www.paperforgeminis.com/minis/1efd9986-a439-415b-94d4-1a9b0227a212",
    folder: "0746",
  },
  {
    id: "747",
    name: "Dead Guard",
    postUrl:
      "https://www.paperforgeminis.com/minis/75261a42-7d98-48ad-8826-f89a900e42b0",
    folder: "0747",
  },
  {
    id: "748",
    name: "Dead Guard",
    postUrl:
      "https://www.paperforgeminis.com/minis/1b167366-0282-48bc-a6ee-f16d4f4fd935",
    folder: "0748",
  },
  {
    id: "749",
    name: "Dead Guard",
    postUrl:
      "https://www.paperforgeminis.com/minis/4ebc3406-656d-4636-a124-8a21b57c7a2f",
    folder: "0749",
  },
  {
    id: "754",
    name: "Arcanist",
    postUrl:
      "https://www.paperforgeminis.com/minis/2a1be1aa-f40d-4894-90eb-2faf09b44743",
    folder: "0754",
  },
  {
    id: "755",
    name: "Arcanist",
    postUrl:
      "https://www.paperforgeminis.com/minis/19c37c59-4cb4-45e4-8dd7-b16ba1b32473",
    folder: "0755",
  },
  {
    id: "758",
    name: "Owlbear",
    postUrl:
      "https://www.paperforgeminis.com/minis/6e04f0b7-31f2-490d-8b2d-4d2fa4aa4740",
    folder: "0758",
  },
  {
    id: "759",
    name: "OwlbearCub",
    postUrl:
      "https://www.paperforgeminis.com/minis/a8225e5c-acc9-4145-9c4d-28c0b249b83f",
    folder: "0759",
  },
  {
    id: "760",
    name: "[Fanart]Ulitharid",
    postUrl:
      "https://www.paperforgeminis.com/minis/2e946ece-9206-4852-8a28-cf1e2028eeaa",
    folder: "0760",
  },
  {
    id: "761",
    name: "Goblin Boss",
    postUrl:
      "https://www.paperforgeminis.com/minis/1ad6624b-4213-4687-9dbd-c5e80d83b558",
    folder: "0761",
  },
  {
    id: "762",
    name: "Goblin Warrior",
    postUrl:
      "https://www.paperforgeminis.com/minis/a0c81d99-91a8-47b4-b307-4ec92335f662",
    folder: "0762",
  },
  {
    id: "763",
    name: "Goblin Warrior",
    postUrl:
      "https://www.paperforgeminis.com/minis/b5685a86-ecc9-4143-8c87-4f513eb8173f",
    folder: "0763",
  },
  {
    id: "764",
    name: "Goblin Hexer",
    postUrl:
      "https://www.paperforgeminis.com/minis/5a84bfe3-f4d9-46fe-98f6-d1a44c748903",
    folder: "0764",
  },
  {
    id: "765",
    name: "Goblin Minion",
    postUrl:
      "https://www.paperforgeminis.com/minis/e212ca92-eec6-4532-bece-408c187d086a",
    folder: "0765",
  },
  {
    id: "766",
    name: "Worg ",
    postUrl:
      "https://www.paperforgeminis.com/minis/59fe0a23-d576-48bf-93b5-c204504140e2",
    folder: "0766",
  },
  {
    id: "768",
    name: "FlamingSkeleton",
    postUrl:
      "https://www.paperforgeminis.com/minis/5f51dc31-1071-418d-966b-82eed52d6f2e",
    folder: "0768",
  },
  {
    id: "769",
    name: "Bugbear Warrior",
    postUrl:
      "https://www.paperforgeminis.com/minis/9966fbaa-a493-4b2e-9be9-2eeb11671c4c",
    folder: "0769",
  },
  {
    id: "770",
    name: "Bugbear Stalker",
    postUrl:
      "https://www.paperforgeminis.com/minis/b4dd686c-277e-4083-b7ae-7f896ef4d218",
    folder: "0770",
  },
  {
    id: "771",
    name: "Hobgoblin Warrior",
    postUrl:
      "https://www.paperforgeminis.com/minis/c4f9f779-a3ea-4efd-a808-9b5168d58b0f",
    folder: "0771",
  },
  {
    id: "772",
    name: "Ghast",
    postUrl:
      "https://www.paperforgeminis.com/minis/86c63cd4-182d-49e9-a24d-3bbbdd0aebb2",
    folder: "0772",
  },
  {
    id: "773",
    name: "Ghast Gravecaller",
    postUrl:
      "https://www.paperforgeminis.com/minis/04f3aa31-04a1-4380-a22a-1eadf002819a",
    folder: "0773",
  },
  {
    id: "774",
    name: "Skeleton",
    postUrl:
      "https://www.paperforgeminis.com/minis/955389ca-e77b-454a-9493-5f9c3f6cca00",
    folder: "0774",
  },
  {
    id: "775",
    name: "Skeleton ",
    postUrl:
      "https://www.paperforgeminis.com/minis/e758ed9e-1787-4864-9dd3-61a1f8d2b9d8",
    folder: "0775",
  },
  {
    id: "776",
    name: "Skeleton",
    postUrl:
      "https://www.paperforgeminis.com/minis/68a45465-4bf2-47b1-8c81-b3ddc90f690f",
    folder: "0776",
  },
  {
    id: "777",
    name: "Skeleton",
    postUrl:
      "https://www.paperforgeminis.com/minis/8b6fd01c-7cf3-4b59-bf8b-46589465147f",
    folder: "0777",
  },
  {
    id: "778",
    name: "Wight",
    postUrl:
      "https://www.paperforgeminis.com/minis/77feb711-81ff-4bf9-8d1d-c69b9b4a37df",
    folder: "0778",
  },
  {
    id: "779",
    name: "Wight",
    postUrl:
      "https://www.paperforgeminis.com/minis/b0c60649-7e60-4627-982d-43c2847612ae",
    folder: "0779",
  },
  {
    id: "780",
    name: "Ogre",
    postUrl:
      "https://www.paperforgeminis.com/minis/9f5a9380-a863-4d75-aec6-56efd36f0cda",
    folder: "0780",
  },
  {
    id: "782",
    name: "Bandit ",
    postUrl:
      "https://www.paperforgeminis.com/minis/5ccba69c-2df0-4d51-ad73-60545bb57b71",
    folder: "0782",
  },
  {
    id: "783",
    name: "Bandit ",
    postUrl:
      "https://www.paperforgeminis.com/minis/9460a16d-ae3e-4198-87d2-e7fa9793b190",
    folder: "0783",
  },
  {
    id: "784",
    name: "Bandit ",
    postUrl:
      "https://www.paperforgeminis.com/minis/b7b0e96e-5a62-4ac8-b7ac-f94b856ab7fc",
    folder: "0784",
  },
  {
    id: "785",
    name: "Bandit Deceiver",
    postUrl:
      "https://www.paperforgeminis.com/minis/5191a71d-5858-401b-b8c7-38a7b1f14c8a",
    folder: "0785",
  },
  {
    id: "786",
    name: "Bandit Captain",
    postUrl:
      "https://www.paperforgeminis.com/minis/cd4119e3-ac56-4767-a781-15746c8fb594",
    folder: "0786",
  },
];

export function getPaperforgeEntry(identifier: string): PaperForgeEntry | null {
  // Try by ID first
  const byId = PAPERFORGE_ENTRIES.find((e) => e.id === identifier);
  if (byId) return byId;

  // Try by name (case-insensitive)
  const byName = PAPERFORGE_ENTRIES.find(
    (e) => e.name.toLowerCase() === identifier.toLowerCase()
  );
  if (byName) return byName;

  return null;
}
