// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package sqldb

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type ArmorType string

const (
	ArmorTypeNone   ArmorType = "none"
	ArmorTypeMedium ArmorType = "medium"
	ArmorTypeHeavy  ArmorType = "heavy"
)

func (e *ArmorType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ArmorType(s)
	case string:
		*e = ArmorType(s)
	default:
		return fmt.Errorf("unsupported scan type for ArmorType: %T", src)
	}
	return nil
}

type NullArmorType struct {
	ArmorType ArmorType
	Valid     bool // Valid is true if ArmorType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullArmorType) Scan(value interface{}) error {
	if value == nil {
		ns.ArmorType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ArmorType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullArmorType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ArmorType), nil
}

type SizeType string

const (
	SizeTypeTiny       SizeType = "tiny"
	SizeTypeSmall      SizeType = "small"
	SizeTypeMedium     SizeType = "medium"
	SizeTypeLarge      SizeType = "large"
	SizeTypeHuge       SizeType = "huge"
	SizeTypeGargantuan SizeType = "gargantuan"
)

func (e *SizeType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = SizeType(s)
	case string:
		*e = SizeType(s)
	default:
		return fmt.Errorf("unsupported scan type for SizeType: %T", src)
	}
	return nil
}

type NullSizeType struct {
	SizeType SizeType
	Valid    bool // Valid is true if SizeType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullSizeType) Scan(value interface{}) error {
	if value == nil {
		ns.SizeType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.SizeType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullSizeType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.SizeType), nil
}

type Monster struct {
	ID        pgtype.UUID
	UserID    pgtype.UUID
	Name      string
	Level     string
	Hp        int32
	Armor     NullArmorType
	Size      NullSizeType
	Speed     pgtype.Int4
	Fly       pgtype.Int4
	Swim      pgtype.Int4
	Actions   [][]byte
	Abilities [][]byte
	Legendary pgtype.Bool
	Bloodied  pgtype.Text
	LastStand pgtype.Text
	Saves     []string
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type Session struct {
	ID        pgtype.UUID
	UserID    pgtype.UUID
	DiscordID string
	ExpiresAt pgtype.Timestamptz
}

type User struct {
	ID        pgtype.UUID
	DiscordID string
	Username  string
	Avatar    pgtype.Text
}
